#!/usr/bin/env python3
"""Build watchlist.json from hardcoded comprehensive lists (network-independent)."""
import json
from pathlib import Path

# ── US: S&P 500 + Nasdaq 100 (deduped) ──────────────────────────────────────
# Format: (symbol, name, exchange, sector)
US_RAW = [
    # Technology
    ("AAPL","Apple Inc.","NASDAQ","Technology"),
    ("MSFT","Microsoft Corp.","NASDAQ","Technology"),
    ("NVDA","NVIDIA Corp.","NASDAQ","Technology"),
    ("AVGO","Broadcom Inc.","NASDAQ","Technology"),
    ("ORCL","Oracle Corp.","NYSE","Technology"),
    ("CRM","Salesforce Inc.","NYSE","Technology"),
    ("CSCO","Cisco Systems","NASDAQ","Technology"),
    ("AMD","Advanced Micro Devices","NASDAQ","Technology"),
    ("INTC","Intel Corp.","NASDAQ","Technology"),
    ("QCOM","Qualcomm Inc.","NASDAQ","Technology"),
    ("TXN","Texas Instruments","NASDAQ","Technology"),
    ("AMAT","Applied Materials","NASDAQ","Technology"),
    ("KLAC","KLA Corp.","NASDAQ","Technology"),
    ("LRCX","Lam Research","NASDAQ","Technology"),
    ("MU","Micron Technology","NASDAQ","Technology"),
    ("SNPS","Synopsys Inc.","NASDAQ","Technology"),
    ("CDNS","Cadence Design","NASDAQ","Technology"),
    ("FTNT","Fortinet Inc.","NASDAQ","Technology"),
    ("ANSS","Ansys Inc.","NASDAQ","Technology"),
    ("PANW","Palo Alto Networks","NASDAQ","Technology"),
    ("ADBE","Adobe Inc.","NASDAQ","Technology"),
    ("NOW","ServiceNow Inc.","NYSE","Technology"),
    ("PLTR","Palantir Technologies","NASDAQ","Technology"),
    ("APP","AppLovin Corp.","NASDAQ","Technology"),
    ("FICO","Fair Isaac Corp.","NYSE","Technology"),
    ("VRSN","VeriSign Inc.","NASDAQ","Technology"),
    ("GEN","Gen Digital","NASDAQ","Technology"),
    ("CDW","CDW Corp.","NASDAQ","Technology"),
    ("WDC","Western Digital","NASDAQ","Technology"),
    ("STX","Seagate Technology","NASDAQ","Technology"),
    ("HPQ","HP Inc.","NYSE","Technology"),
    ("HPE","Hewlett Packard Enterprise","NYSE","Technology"),
    ("NTAP","NetApp Inc.","NASDAQ","Technology"),
    ("JNPR","Juniper Networks","NYSE","Technology"),
    ("ZBRA","Zebra Technologies","NASDAQ","Technology"),
    ("KEYS","Keysight Technologies","NYSE","Technology"),
    ("TRMB","Trimble Inc.","NASDAQ","Technology"),
    ("PAYC","Paycom Software","NYSE","Technology"),
    ("GDDY","GoDaddy Inc.","NYSE","Technology"),
    ("ROP","Roper Technologies","NASDAQ","Technology"),
    ("EPAM","EPAM Systems","NYSE","Technology"),
    ("ACN","Accenture plc","NYSE","Technology"),
    ("IBM","IBM Corp.","NYSE","Technology"),
    ("CTSH","Cognizant Technology","NASDAQ","Technology"),
    ("IT","Gartner Inc.","NYSE","Technology"),
    ("MSI","Motorola Solutions","NYSE","Technology"),
    ("LDOS","Leidos Holdings","NYSE","Technology"),
    ("AKAM","Akamai Technologies","NASDAQ","Technology"),
    ("GLW","Corning Inc.","NYSE","Technology"),
    ("TDY","Teledyne Technologies","NYSE","Technology"),
    ("NXPI","NXP Semiconductors","NASDAQ","Technology"),
    ("MCHP","Microchip Technology","NASDAQ","Technology"),
    ("ON","ON Semiconductor","NASDAQ","Technology"),
    ("TER","Teradyne Inc.","NASDAQ","Technology"),
    ("MPWR","Monolithic Power Systems","NASDAQ","Technology"),
    ("SWKS","Skyworks Solutions","NASDAQ","Technology"),
    ("QRVO","Qorvo Inc.","NASDAQ","Technology"),
    ("ENPH","Enphase Energy","NASDAQ","Technology"),
    ("SEDG","SolarEdge Technologies","NASDAQ","Technology"),
    ("FSLR","First Solar","NASDAQ","Technology"),
    ("SMCI","Super Micro Computer","NASDAQ","Technology"),
    ("DECK","Deckers Outdoor","NYSE","Consumer Disc."),
    ("AXON","Axon Enterprise","NASDAQ","Technology"),
    ("DDOG","Datadog Inc.","NASDAQ","Technology"),
    ("ZS","Zscaler Inc.","NASDAQ","Technology"),
    ("CRWD","CrowdStrike Holdings","NASDAQ","Technology"),
    ("MDB","MongoDB Inc.","NASDAQ","Technology"),
    ("SNOW","Snowflake Inc.","NYSE","Technology"),
    ("OKTA","Okta Inc.","NASDAQ","Technology"),
    ("VEEV","Veeva Systems","NYSE","Technology"),
    ("TEAM","Atlassian Corp.","NASDAQ","Technology"),
    ("WDAY","Workday Inc.","NASDAQ","Technology"),
    ("HUBS","HubSpot Inc.","NYSE","Technology"),
    ("DOCU","DocuSign Inc.","NASDAQ","Technology"),
    ("ZM","Zoom Video","NASDAQ","Technology"),
    ("TWLO","Twilio Inc.","NYSE","Technology"),
    ("NET","Cloudflare Inc.","NYSE","Technology"),
    ("GTLB","GitLab Inc.","NASDAQ","Technology"),
    # Communication Services
    ("META","Meta Platforms","NASDAQ","Communication"),
    ("GOOGL","Alphabet Inc. Class A","NASDAQ","Communication"),
    ("GOOG","Alphabet Inc. Class C","NASDAQ","Communication"),
    ("NFLX","Netflix Inc.","NASDAQ","Communication"),
    ("DIS","Walt Disney Co.","NYSE","Communication"),
    ("CMCSA","Comcast Corp.","NASDAQ","Communication"),
    ("VZ","Verizon Communications","NYSE","Communication"),
    ("T","AT&T Inc.","NYSE","Communication"),
    ("TMUS","T-Mobile US","NASDAQ","Communication"),
    ("CHTR","Charter Communications","NASDAQ","Communication"),
    ("WBD","Warner Bros. Discovery","NASDAQ","Communication"),
    ("FOX","Fox Corp. Class B","NASDAQ","Communication"),
    ("FOXA","Fox Corp. Class A","NASDAQ","Communication"),
    ("NWS","News Corp. Class B","NASDAQ","Communication"),
    ("NWSA","News Corp. Class A","NASDAQ","Communication"),
    ("OMC","Omnicom Group","NYSE","Communication"),
    ("IPG","Interpublic Group","NYSE","Communication"),
    ("LYV","Live Nation Entertainment","NYSE","Communication"),
    ("EA","Electronic Arts","NASDAQ","Communication"),
    ("TTWO","Take-Two Interactive","NASDAQ","Communication"),
    # Consumer Discretionary
    ("AMZN","Amazon.com Inc.","NASDAQ","Consumer Disc."),
    ("TSLA","Tesla Inc.","NASDAQ","Consumer Disc."),
    ("MCD","McDonald's Corp.","NYSE","Consumer Disc."),
    ("NKE","Nike Inc.","NYSE","Consumer Disc."),
    ("SBUX","Starbucks Corp.","NASDAQ","Consumer Disc."),
    ("TGT","Target Corp.","NYSE","Consumer Disc."),
    ("HD","Home Depot","NYSE","Consumer Disc."),
    ("LOW","Lowe's Companies","NYSE","Consumer Disc."),
    ("TJX","TJX Companies","NYSE","Consumer Disc."),
    ("ROST","Ross Stores","NASDAQ","Consumer Disc."),
    ("BKNG","Booking Holdings","NASDAQ","Consumer Disc."),
    ("ABNB","Airbnb Inc.","NASDAQ","Consumer Disc."),
    ("MAR","Marriott International","NASDAQ","Consumer Disc."),
    ("HLT","Hilton Worldwide","NYSE","Consumer Disc."),
    ("YUM","Yum! Brands","NYSE","Consumer Disc."),
    ("CMG","Chipotle Mexican Grill","NYSE","Consumer Disc."),
    ("DRI","Darden Restaurants","NYSE","Consumer Disc."),
    ("EXPE","Expedia Group","NASDAQ","Consumer Disc."),
    ("EBAY","eBay Inc.","NASDAQ","Consumer Disc."),
    ("ETSY","Etsy Inc.","NASDAQ","Consumer Disc."),
    ("PHM","PulteGroup Inc.","NYSE","Consumer Disc."),
    ("DHI","D.R. Horton","NYSE","Consumer Disc."),
    ("LEN","Lennar Corp.","NYSE","Consumer Disc."),
    ("NVR","NVR Inc.","NYSE","Consumer Disc."),
    ("TOL","Toll Brothers","NYSE","Consumer Disc."),
    ("GM","General Motors","NYSE","Consumer Disc."),
    ("F","Ford Motor Co.","NYSE","Consumer Disc."),
    ("RIVN","Rivian Automotive","NASDAQ","Consumer Disc."),
    ("LCID","Lucid Group","NASDAQ","Consumer Disc."),
    ("BWA","BorgWarner Inc.","NYSE","Consumer Disc."),
    ("APTV","Aptiv PLC","NYSE","Consumer Disc."),
    ("LKQ","LKQ Corp.","NASDAQ","Consumer Disc."),
    ("AZO","AutoZone Inc.","NYSE","Consumer Disc."),
    ("AAP","Advance Auto Parts","NYSE","Consumer Disc."),
    ("ORLY","O'Reilly Automotive","NASDAQ","Consumer Disc."),
    ("GPC","Genuine Parts","NYSE","Consumer Disc."),
    ("BBY","Best Buy Co.","NYSE","Consumer Disc."),
    ("KMX","CarMax Inc.","NYSE","Consumer Disc."),
    ("AN","AutoNation Inc.","NYSE","Consumer Disc."),
    ("PAG","Penske Automotive","NYSE","Consumer Disc."),
    ("RL","Ralph Lauren Corp.","NYSE","Consumer Disc."),
    ("PVH","PVH Corp.","NYSE","Consumer Disc."),
    ("HBI","Hanesbrands Inc.","NYSE","Consumer Disc."),
    ("TPR","Tapestry Inc.","NYSE","Consumer Disc."),
    ("CPRI","Capri Holdings","NYSE","Consumer Disc."),
    ("MGM","MGM Resorts","NYSE","Consumer Disc."),
    ("WYNN","Wynn Resorts","NASDAQ","Consumer Disc."),
    ("LVS","Las Vegas Sands","NYSE","Consumer Disc."),
    ("CZR","Caesars Entertainment","NASDAQ","Consumer Disc."),
    ("RCL","Royal Caribbean","NYSE","Consumer Disc."),
    ("CCL","Carnival Corp.","NYSE","Consumer Disc."),
    ("NCLH","Norwegian Cruise Line","NYSE","Consumer Disc."),
    ("UAL","United Airlines","NASDAQ","Consumer Disc."),
    ("DAL","Delta Air Lines","NYSE","Consumer Disc."),
    ("AAL","American Airlines","NASDAQ","Consumer Disc."),
    ("LUV","Southwest Airlines","NYSE","Consumer Disc."),
    ("ALK","Alaska Air Group","NYSE","Consumer Disc."),
    ("ULTA","Ulta Beauty","NASDAQ","Consumer Disc."),
    ("LULU","lululemon athletica","NASDAQ","Consumer Disc."),
    ("VFC","VF Corp.","NYSE","Consumer Disc."),
    ("COLM","Columbia Sportswear","NASDAQ","Consumer Disc."),
    ("HAS","Hasbro Inc.","NASDAQ","Consumer Disc."),
    ("MAT","Mattel Inc.","NASDAQ","Consumer Disc."),
    # Consumer Staples
    ("PG","Procter & Gamble","NYSE","Consumer Staples"),
    ("KO","Coca-Cola Co.","NYSE","Consumer Staples"),
    ("PEP","PepsiCo Inc.","NASDAQ","Consumer Staples"),
    ("WMT","Walmart Inc.","NYSE","Consumer Staples"),
    ("COST","Costco Wholesale","NASDAQ","Consumer Staples"),
    ("PM","Philip Morris International","NYSE","Consumer Staples"),
    ("MO","Altria Group","NYSE","Consumer Staples"),
    ("EL","Estée Lauder","NYSE","Consumer Staples"),
    ("CL","Colgate-Palmolive","NYSE","Consumer Staples"),
    ("GIS","General Mills","NYSE","Consumer Staples"),
    ("K","Kellanova","NYSE","Consumer Staples"),
    ("CPB","Campbell Soup","NYSE","Consumer Staples"),
    ("MKC","McCormick & Co.","NYSE","Consumer Staples"),
    ("SJM","J.M. Smucker","NYSE","Consumer Staples"),
    ("HRL","Hormel Foods","NYSE","Consumer Staples"),
    ("CAG","Conagra Brands","NYSE","Consumer Staples"),
    ("CHD","Church & Dwight","NYSE","Consumer Staples"),
    ("CLX","Clorox Co.","NYSE","Consumer Staples"),
    ("TSN","Tyson Foods","NYSE","Consumer Staples"),
    ("KR","Kroger Co.","NYSE","Consumer Staples"),
    ("SFM","Sprouts Farmers Market","NASDAQ","Consumer Staples"),
    ("KHC","Kraft Heinz Co.","NASDAQ","Consumer Staples"),
    ("MNST","Monster Beverage","NASDAQ","Consumer Staples"),
    ("STZ","Constellation Brands","NYSE","Consumer Staples"),
    ("BF-B","Brown-Forman Corp.","NYSE","Consumer Staples"),
    ("TAP","Molson Coors Beverage","NYSE","Consumer Staples"),
    ("SAM","Boston Beer Co.","NYSE","Consumer Staples"),
    ("SYY","Sysco Corp.","NYSE","Consumer Staples"),
    ("PFGC","Performance Food Group","NYSE","Consumer Staples"),
    ("USF","US Foods Holding","NYSE","Consumer Staples"),
    # Financials
    ("BRK-B","Berkshire Hathaway B","NYSE","Financials"),
    ("JPM","JPMorgan Chase","NYSE","Financials"),
    ("V","Visa Inc.","NYSE","Financials"),
    ("MA","Mastercard Inc.","NYSE","Financials"),
    ("BAC","Bank of America","NYSE","Financials"),
    ("WFC","Wells Fargo","NYSE","Financials"),
    ("GS","Goldman Sachs","NYSE","Financials"),
    ("MS","Morgan Stanley","NYSE","Financials"),
    ("BLK","BlackRock Inc.","NYSE","Financials"),
    ("SCHW","Charles Schwab","NYSE","Financials"),
    ("AXP","American Express","NYSE","Financials"),
    ("COF","Capital One Financial","NYSE","Financials"),
    ("USB","U.S. Bancorp","NYSE","Financials"),
    ("PNC","PNC Financial Services","NYSE","Financials"),
    ("TFC","Truist Financial","NYSE","Financials"),
    ("SPGI","S&P Global Inc.","NYSE","Financials"),
    ("MCO","Moody's Corp.","NYSE","Financials"),
    ("ICE","Intercontinental Exchange","NYSE","Financials"),
    ("CME","CME Group","NASDAQ","Financials"),
    ("NDAQ","Nasdaq Inc.","NASDAQ","Financials"),
    ("CB","Chubb Ltd.","NYSE","Financials"),
    ("TRV","Travelers Companies","NYSE","Financials"),
    ("ALL","Allstate Corp.","NYSE","Financials"),
    ("PGR","Progressive Corp.","NYSE","Financials"),
    ("AIG","American International Group","NYSE","Financials"),
    ("MET","MetLife Inc.","NYSE","Financials"),
    ("PRU","Prudential Financial","NYSE","Financials"),
    ("AFL","Aflac Inc.","NYSE","Financials"),
    ("HIG","Hartford Financial","NYSE","Financials"),
    ("GL","Globe Life Inc.","NYSE","Financials"),
    ("LNC","Lincoln National","NYSE","Financials"),
    ("UNM","Unum Group","NYSE","Financials"),
    ("RNR","RenaissanceRe Holdings","NYSE","Financials"),
    ("FNF","Fidelity National Financial","NYSE","Financials"),
    ("FAF","First American Financial","NYSE","Financials"),
    ("MTB","M&T Bank Corp.","NYSE","Financials"),
    ("RF","Regions Financial","NYSE","Financials"),
    ("CFG","Citizens Financial Group","NYSE","Financials"),
    ("HBAN","Huntington Bancshares","NASDAQ","Financials"),
    ("KEY","KeyCorp","NYSE","Financials"),
    ("FITB","Fifth Third Bancorp","NASDAQ","Financials"),
    ("ZION","Zions Bancorporation","NASDAQ","Financials"),
    ("CMA","Comerica Inc.","NASDAQ","Financials"),
    ("SNV","Synovus Financial","NYSE","Financials"),
    ("FHN","First Horizon Corp.","NYSE","Financials"),
    ("WBS","Webster Financial","NYSE","Financials"),
    ("EWBC","East West Bancorp","NASDAQ","Financials"),
    ("FCNCA","First Citizens BancShares","NASDAQ","Financials"),
    ("WAL","Western Alliance Bancorporation","NYSE","Financials"),
    ("PACW","PacWest Bancorp","NASDAQ","Financials"),
    ("FRC","First Republic Bank","NYSE","Financials"),
    ("SIVB","SVB Financial Group","NASDAQ","Financials"),
    ("CBSH","Commerce Bancshares","NASDAQ","Financials"),
    ("BOKF","BOK Financial","NASDAQ","Financials"),
    ("OFG","OFG Bancorp","NYSE","Financials"),
    ("GPN","Global Payments","NYSE","Financials"),
    ("FIS","Fidelity National Info. Svcs.","NYSE","Financials"),
    ("FISV","Fiserv Inc.","NASDAQ","Financials"),
    ("PYPL","PayPal Holdings","NASDAQ","Financials"),
    ("SQ","Block Inc.","NYSE","Financials"),
    ("AFRM","Affirm Holdings","NASDAQ","Financials"),
    ("SOFI","SoFi Technologies","NASDAQ","Financials"),
    ("LC","LendingClub Corp.","NYSE","Financials"),
    ("UPST","Upstart Holdings","NASDAQ","Financials"),
    ("MKTX","MarketAxess Holdings","NASDAQ","Financials"),
    ("IBKR","Interactive Brokers","NASDAQ","Financials"),
    ("LPLA","LPL Financial Holdings","NASDAQ","Financials"),
    ("RJF","Raymond James Financial","NYSE","Financials"),
    ("SF","Stifel Financial","NYSE","Financials"),
    # Healthcare
    ("LLY","Eli Lilly","NYSE","Healthcare"),
    ("JNJ","Johnson & Johnson","NYSE","Healthcare"),
    ("MRK","Merck & Co.","NYSE","Healthcare"),
    ("ABBV","AbbVie Inc.","NYSE","Healthcare"),
    ("PFE","Pfizer Inc.","NYSE","Healthcare"),
    ("ABT","Abbott Laboratories","NYSE","Healthcare"),
    ("TMO","Thermo Fisher Scientific","NYSE","Healthcare"),
    ("MDT","Medtronic PLC","NYSE","Healthcare"),
    ("UNH","UnitedHealth Group","NYSE","Healthcare"),
    ("CVS","CVS Health Corp.","NYSE","Healthcare"),
    ("CI","Cigna Group","NYSE","Healthcare"),
    ("HUM","Humana Inc.","NYSE","Healthcare"),
    ("ELV","Elevance Health","NYSE","Healthcare"),
    ("CNC","Centene Corp.","NYSE","Healthcare"),
    ("MOH","Molina Healthcare","NYSE","Healthcare"),
    ("AMGN","Amgen Inc.","NASDAQ","Healthcare"),
    ("GILD","Gilead Sciences","NASDAQ","Healthcare"),
    ("BIIB","Biogen Inc.","NASDAQ","Healthcare"),
    ("REGN","Regeneron Pharmaceuticals","NASDAQ","Healthcare"),
    ("VRTX","Vertex Pharmaceuticals","NASDAQ","Healthcare"),
    ("MRNA","Moderna Inc.","NASDAQ","Healthcare"),
    ("BMY","Bristol-Myers Squibb","NYSE","Healthcare"),
    ("ZBH","Zimmer Biomet","NYSE","Healthcare"),
    ("BDX","Becton Dickinson","NYSE","Healthcare"),
    ("IQV","IQVIA Holdings","NYSE","Healthcare"),
    ("SYK","Stryker Corp.","NYSE","Healthcare"),
    ("BSX","Boston Scientific","NYSE","Healthcare"),
    ("EW","Edwards Lifesciences","NYSE","Healthcare"),
    ("HOLX","Hologic Inc.","NASDAQ","Healthcare"),
    ("DXCM","Dexcom Inc.","NASDAQ","Healthcare"),
    ("PODD","Insulet Corp.","NASDAQ","Healthcare"),
    ("RMD","ResMed Inc.","NYSE","Healthcare"),
    ("ALGN","Align Technology","NASDAQ","Healthcare"),
    ("IDXX","IDEXX Laboratories","NASDAQ","Healthcare"),
    ("MCK","McKesson Corp.","NYSE","Healthcare"),
    ("ABC","AmerisourceBergen","NYSE","Healthcare"),
    ("CAH","Cardinal Health","NYSE","Healthcare"),
    ("ISRG","Intuitive Surgical","NASDAQ","Healthcare"),
    ("HSIC","Henry Schein","NASDAQ","Healthcare"),
    ("WAT","Waters Corp.","NYSE","Healthcare"),
    ("A","Agilent Technologies","NYSE","Healthcare"),
    ("CRL","Charles River Laboratories","NYSE","Healthcare"),
    ("MTD","Mettler-Toledo","NYSE","Healthcare"),
    ("BAX","Baxter International","NYSE","Healthcare"),
    ("BIO","Bio-Rad Laboratories","NYSE","Healthcare"),
    ("TECH","Bio-Techne Corp.","NASDAQ","Healthcare"),
    ("ZTS","Zoetis Inc.","NYSE","Healthcare"),
    ("VTRS","Viatris Inc.","NASDAQ","Healthcare"),
    ("PRGO","Perrigo Co.","NYSE","Healthcare"),
    ("JAZZ","Jazz Pharmaceuticals","NASDAQ","Healthcare"),
    ("INCY","Incyte Corp.","NASDAQ","Healthcare"),
    ("BMRN","BioMarin Pharmaceutical","NASDAQ","Healthcare"),
    ("SRPT","Sarepta Therapeutics","NASDAQ","Healthcare"),
    ("ALNY","Alnylam Pharmaceuticals","NASDAQ","Healthcare"),
    ("ARGX","argenx SE","NASDAQ","Healthcare"),
    ("RPRX","Royalty Pharma","NASDAQ","Healthcare"),
    ("HCA","HCA Healthcare","NYSE","Healthcare"),
    ("THC","Tenet Healthcare","NYSE","Healthcare"),
    ("UHS","Universal Health Services","NYSE","Healthcare"),
    ("CYH","Community Health Systems","NYSE","Healthcare"),
    ("ENSG","Ensign Group","NASDAQ","Healthcare"),
    ("SEM","Select Medical Holdings","NYSE","Healthcare"),
    ("AMED","Amedisys Inc.","NASDAQ","Healthcare"),
    ("DVA","DaVita Inc.","NYSE","Healthcare"),
    # Energy
    ("XOM","Exxon Mobil","NYSE","Energy"),
    ("CVX","Chevron Corp.","NYSE","Energy"),
    ("COP","ConocoPhillips","NYSE","Energy"),
    ("EOG","EOG Resources","NYSE","Energy"),
    ("SLB","SLB (Schlumberger)","NYSE","Energy"),
    ("OXY","Occidental Petroleum","NYSE","Energy"),
    ("PSX","Phillips 66","NYSE","Energy"),
    ("VLO","Valero Energy","NYSE","Energy"),
    ("MPC","Marathon Petroleum","NYSE","Energy"),
    ("HES","Hess Corp.","NYSE","Energy"),
    ("DVN","Devon Energy","NYSE","Energy"),
    ("HAL","Halliburton Co.","NYSE","Energy"),
    ("BKR","Baker Hughes","NASDAQ","Energy"),
    ("FANG","Diamondback Energy","NASDAQ","Energy"),
    ("APA","APA Corp.","NASDAQ","Energy"),
    ("MRO","Marathon Oil","NYSE","Energy"),
    ("CTRA","Coterra Energy","NYSE","Energy"),
    ("PR","Permian Resources","NYSE","Energy"),
    ("SM","SM Energy","NYSE","Energy"),
    ("RRC","Range Resources","NYSE","Energy"),
    ("EQT","EQT Corp.","NYSE","Energy"),
    ("AR","Antero Resources","NYSE","Energy"),
    ("KMI","Kinder Morgan","NYSE","Energy"),
    ("OKE","ONEOK Inc.","NYSE","Energy"),
    ("WMB","Williams Companies","NYSE","Energy"),
    ("ET","Energy Transfer LP","NYSE","Energy"),
    ("EPD","Enterprise Products Partners","NYSE","Energy"),
    ("MMP","Magellan Midstream","NYSE","Energy"),
    ("TRGP","Targa Resources","NYSE","Energy"),
    ("AM","Antero Midstream","NYSE","Energy"),
    # Industrials
    ("HON","Honeywell International","NASDAQ","Industrials"),
    ("UPS","United Parcel Service","NYSE","Industrials"),
    ("RTX","RTX Corp.","NYSE","Industrials"),
    ("LMT","Lockheed Martin","NYSE","Industrials"),
    ("GD","General Dynamics","NYSE","Industrials"),
    ("NOC","Northrop Grumman","NYSE","Industrials"),
    ("BA","Boeing Co.","NYSE","Industrials"),
    ("CAT","Caterpillar Inc.","NYSE","Industrials"),
    ("DE","Deere & Co.","NYSE","Industrials"),
    ("EMR","Emerson Electric","NYSE","Industrials"),
    ("ETN","Eaton Corp.","NYSE","Industrials"),
    ("ROK","Rockwell Automation","NYSE","Industrials"),
    ("AME","AMETEK Inc.","NYSE","Industrials"),
    ("FTV","Fortive Corp.","NYSE","Industrials"),
    ("GE","GE Aerospace","NYSE","Industrials"),
    ("GEV","GE Vernova","NYSE","Industrials"),
    ("MMM","3M Co.","NYSE","Industrials"),
    ("ITW","Illinois Tool Works","NASDAQ","Industrials"),
    ("PPG","PPG Industries","NYSE","Industrials"),
    ("PH","Parker Hannifin","NYSE","Industrials"),
    ("IR","Ingersoll Rand","NYSE","Industrials"),
    ("XYL","Xylem Inc.","NYSE","Industrials"),
    ("PCAR","PACCAR Inc.","NASDAQ","Industrials"),
    ("OTIS","Otis Worldwide","NYSE","Industrials"),
    ("CARR","Carrier Global","NYSE","Industrials"),
    ("TT","Trane Technologies","NYSE","Industrials"),
    ("JCI","Johnson Controls","NYSE","Industrials"),
    ("AOS","A.O. Smith Corp.","NYSE","Industrials"),
    ("PNR","Pentair PLC","NYSE","Industrials"),
    ("NDSN","Nordson Corp.","NASDAQ","Industrials"),
    ("HUBB","Hubbell Inc.","NYSE","Industrials"),
    ("RXO","RXO Inc.","NYSE","Industrials"),
    ("FDX","FedEx Corp.","NYSE","Industrials"),
    ("EXPD","Expeditors Intl.","NASDAQ","Industrials"),
    ("CH","C.H. Robinson","NASDAQ","Industrials"),
    ("XPO","XPO Inc.","NYSE","Industrials"),
    ("SAIA","Saia Inc.","NASDAQ","Industrials"),
    ("ODFL","Old Dominion Freight Line","NASDAQ","Industrials"),
    ("JBHT","J.B. Hunt Transport","NASDAQ","Industrials"),
    ("KNX","Knight-Swift Transportation","NYSE","Industrials"),
    ("R","Ryder System","NYSE","Industrials"),
    ("CHRW","C.H. Robinson Worldwide","NASDAQ","Industrials"),
    ("NSC","Norfolk Southern","NYSE","Industrials"),
    ("UNP","Union Pacific","NYSE","Industrials"),
    ("CSX","CSX Corp.","NASDAQ","Industrials"),
    ("CP","Canadian Pacific Kansas City","NYSE","Industrials"),
    ("CNI","Canadian National Railway","NYSE","Industrials"),
    ("WAB","Wabtec Corp.","NYSE","Industrials"),
    ("GWW","W.W. Grainger","NYSE","Industrials"),
    ("MSC","MSC Industrial Direct","NYSE","Industrials"),
    ("FAST","Fastenal Co.","NASDAQ","Industrials"),
    ("WSO","Watsco Inc.","NYSE","Industrials"),
    ("GNRC","Generac Holdings","NYSE","Industrials"),
    ("AXTA","Axalta Coating Systems","NYSE","Industrials"),
    ("TKR","Timken Co.","NYSE","Industrials"),
    ("RRX","Rexnord Corp.","NYSE","Industrials"),
    ("AYI","Acuity Brands","NYSE","Industrials"),
    ("ALLE","Allegion PLC","NYSE","Industrials"),
    ("CSGP","CoStar Group","NASDAQ","Industrials"),
    ("EFX","Equifax Inc.","NYSE","Industrials"),
    ("TRI","Thomson Reuters","NYSE","Industrials"),
    ("VRSK","Verisk Analytics","NASDAQ","Industrials"),
    ("CPRT","Copart Inc.","NASDAQ","Industrials"),
    ("CTAS","Cintas Corp.","NASDAQ","Industrials"),
    ("ADP","Automatic Data Processing","NASDAQ","Industrials"),
    ("PAYX","Paychex Inc.","NASDAQ","Industrials"),
    ("BR","Broadridge Financial","NYSE","Industrials"),
    ("LDOS","Leidos Holdings","NYSE","Industrials"),
    ("SAIC","Science Applications Intl.","NYSE","Industrials"),
    ("BAH","Booz Allen Hamilton","NYSE","Industrials"),
    ("CACI","CACI International","NYSE","Industrials"),
    ("CSRA","CSRA Inc.","NYSE","Industrials"),
    ("ICF","Insight Direct","NASDAQ","Industrials"),
    ("TDG","TransDigm Group","NYSE","Industrials"),
    ("SPR","Spirit AeroSystems","NYSE","Industrials"),
    ("HEI","HEICO Corp.","NYSE","Industrials"),
    ("KTOS","Kratos Defense","NASDAQ","Industrials"),
    ("MOOG","Moog Inc.","NYSE","Industrials"),
    ("CW","Curtiss-Wright","NYSE","Industrials"),
    ("HII","Huntington Ingalls","NYSE","Industrials"),
    ("LHX","L3Harris Technologies","NYSE","Industrials"),
    ("MRCY","Mercury Systems","NASDAQ","Industrials"),
    ("AWK","American Water Works","NYSE","Utilities"),
    # Materials
    ("LIN","Linde PLC","NASDAQ","Materials"),
    ("APD","Air Products & Chemicals","NASDAQ","Materials"),
    ("SHW","Sherwin-Williams","NYSE","Materials"),
    ("NEM","Newmont Corp.","NYSE","Materials"),
    ("FCX","Freeport-McMoRan","NYSE","Materials"),
    ("NUE","Nucor Corp.","NYSE","Materials"),
    ("VMC","Vulcan Materials","NYSE","Materials"),
    ("MLM","Martin Marietta Materials","NYSE","Materials"),
    ("ECL","Ecolab Inc.","NYSE","Materials"),
    ("DD","DuPont de Nemours","NYSE","Materials"),
    ("DOW","Dow Inc.","NYSE","Materials"),
    ("CE","Celanese Corp.","NYSE","Materials"),
    ("ALB","Albemarle Corp.","NYSE","Materials"),
    ("MOS","Mosaic Co.","NYSE","Materials"),
    ("CF","CF Industries","NYSE","Materials"),
    ("IFF","International Flavors & Fragrances","NYSE","Materials"),
    ("RPM","RPM International","NYSE","Materials"),
    ("AVY","Avery Dennison","NYSE","Materials"),
    ("SEE","Sealed Air Corp.","NYSE","Materials"),
    ("PKG","Packaging Corp. of America","NYSE","Materials"),
    ("IP","International Paper","NYSE","Materials"),
    ("WRK","WestRock Co.","NYSE","Materials"),
    ("ATI","ATI Inc.","NYSE","Materials"),
    ("RS","Reliance Steel & Aluminum","NYSE","Materials"),
    ("STLD","Steel Dynamics","NASDAQ","Materials"),
    ("CMC","Commercial Metals","NYSE","Materials"),
    ("X","United States Steel","NYSE","Materials"),
    ("CLF","Cleveland-Cliffs","NYSE","Materials"),
    ("AA","Alcoa Corp.","NYSE","Materials"),
    ("HUN","Huntsman Corp.","NYSE","Materials"),
    ("OLN","Olin Corp.","NYSE","Materials"),
    ("EMN","Eastman Chemical","NYSE","Materials"),
    ("FMC","FMC Corp.","NYSE","Materials"),
    ("GRA","W.R. Grace","NYSE","Materials"),
    # Utilities
    ("NEE","NextEra Energy","NYSE","Utilities"),
    ("DUK","Duke Energy","NYSE","Utilities"),
    ("SO","Southern Co.","NYSE","Utilities"),
    ("D","Dominion Energy","NYSE","Utilities"),
    ("AEP","American Electric Power","NASDAQ","Utilities"),
    ("XEL","Xcel Energy","NASDAQ","Utilities"),
    ("EXC","Exelon Corp.","NASDAQ","Utilities"),
    ("PCG","PG&E Corp.","NYSE","Utilities"),
    ("ED","Consolidated Edison","NYSE","Utilities"),
    ("FE","FirstEnergy Corp.","NYSE","Utilities"),
    ("ETR","Entergy Corp.","NYSE","Utilities"),
    ("WEC","WEC Energy Group","NYSE","Utilities"),
    ("ES","Eversource Energy","NYSE","Utilities"),
    ("EIX","Edison International","NYSE","Utilities"),
    ("PEG","Public Service Enterprise","NYSE","Utilities"),
    ("CEG","Constellation Energy","NASDAQ","Utilities"),
    ("CMS","CMS Energy","NYSE","Utilities"),
    ("LNT","Alliant Energy","NASDAQ","Utilities"),
    ("EVRG","Evergy Inc.","NASDAQ","Utilities"),
    ("NI","NiSource Inc.","NYSE","Utilities"),
    ("PPL","PPL Corp.","NYSE","Utilities"),
    ("OGE","OGE Energy","NYSE","Utilities"),
    ("AEE","Ameren Corp.","NYSE","Utilities"),
    ("WTRG","Essential Utilities","NYSE","Utilities"),
    ("SRE","Sempra","NYSE","Utilities"),
    ("PNW","Pinnacle West Capital","NASDAQ","Utilities"),
    ("IDA","IDACORP Inc.","NYSE","Utilities"),
    ("NWE","NorthWestern Energy","NASDAQ","Utilities"),
    ("ATO","Atmos Energy","NYSE","Utilities"),
    ("CNP","CenterPoint Energy","NYSE","Utilities"),
    ("UGI","UGI Corp.","NYSE","Utilities"),
    ("SR","Spire Inc.","NYSE","Utilities"),
    ("NJR","New Jersey Resources","NYSE","Utilities"),
    ("SWX","Southwest Gas Holdings","NYSE","Utilities"),
    ("OGS","ONE Gas Inc.","NYSE","Utilities"),
    # Real Estate
    ("AMT","American Tower","NYSE","Real Estate"),
    ("PLD","Prologis Inc.","NYSE","Real Estate"),
    ("CCI","Crown Castle","NYSE","Real Estate"),
    ("EQIX","Equinix Inc.","NASDAQ","Real Estate"),
    ("SPG","Simon Property Group","NYSE","Real Estate"),
    ("O","Realty Income Corp.","NYSE","Real Estate"),
    ("WELL","Welltower Inc.","NYSE","Real Estate"),
    ("PSA","Public Storage","NYSE","Real Estate"),
    ("DLR","Digital Realty Trust","NYSE","Real Estate"),
    ("EQR","Equity Residential","NYSE","Real Estate"),
    ("MAA","Mid-America Apartment","NYSE","Real Estate"),
    ("UDR","UDR Inc.","NYSE","Real Estate"),
    ("AVB","AvalonBay Communities","NYSE","Real Estate"),
    ("ESS","Essex Property Trust","NYSE","Real Estate"),
    ("VTR","Ventas Inc.","NYSE","Real Estate"),
    ("BXP","Boston Properties","NYSE","Real Estate"),
    ("KIM","Kimco Realty","NYSE","Real Estate"),
    ("REG","Regency Centers","NASDAQ","Real Estate"),
    ("HST","Host Hotels & Resorts","NASDAQ","Real Estate"),
    ("SLG","SL Green Realty","NYSE","Real Estate"),
    ("ARE","Alexandria Real Estate","NYSE","Real Estate"),
    ("VICI","VICI Properties","NYSE","Real Estate"),
    ("GLPI","Gaming and Leisure Properties","NASDAQ","Real Estate"),
    ("MPW","Medical Properties Trust","NYSE","Real Estate"),
    ("PEAK","Healthpeak Properties","NYSE","Real Estate"),
    ("HR","Healthcare Realty Trust","NYSE","Real Estate"),
    ("DOC","Physicians Realty Trust","NYSE","Real Estate"),
    ("IRM","Iron Mountain","NYSE","Real Estate"),
    ("COLD","Americold Realty Trust","NYSE","Real Estate"),
    ("REXR","Rexford Industrial Realty","NYSE","Real Estate"),
    ("EGP","EastGroup Properties","NASDAQ","Real Estate"),
    ("FR","First Industrial Realty","NYSE","Real Estate"),
    ("WY","Weyerhaeuser Co.","NYSE","Real Estate"),
    ("PotlatchDeltic","PotlatchDeltic Corp.","NASDAQ","Real Estate"),
    ("PCH","PotlatchDeltic Corp.","NASDAQ","Real Estate"),
    ("NNN","NNN REIT","NYSE","Real Estate"),
    ("ADC","Agree Realty","NYSE","Real Estate"),
    ("EPRT","Essential Properties Realty","NYSE","Real Estate"),
    ("GTY","Getty Realty","NYSE","Real Estate"),
    ("STOR","STORE Capital","NYSE","Real Estate"),
    ("WPC","W. P. Carey","NYSE","Real Estate"),
    ("CTO","CTO Realty Growth","NYSE","Real Estate"),
    ("SKT","Tanger Factory Outlet","NYSE","Real Estate"),
    ("MAC","Macerich Co.","NYSE","Real Estate"),
    ("CBL","CBL & Associates","NYSE","Real Estate"),
]

def us_entry(symbol, name, exchange, sector):
    yahoo = symbol
    tv = f"{exchange}:{symbol.replace('-','.')}"
    return {"symbol": symbol, "name": name, "yahooSuffix": yahoo, "tvSymbol": tv, "sector": sector}

def build_us():
    seen = set()
    out = []
    for row in US_RAW:
        sym = row[0]
        if sym not in seen:
            seen.add(sym)
            out.append(us_entry(*row))
    return out

# ── India: Nifty 500 ─────────────────────────────────────────────────────────
# Format: (symbol, name, sector)
INDIA_RAW = [
    # Nifty 50
    ("RELIANCE","Reliance Industries","Energy"),
    ("TCS","Tata Consultancy Services","Technology"),
    ("HDFCBANK","HDFC Bank","Financials"),
    ("INFY","Infosys Ltd.","Technology"),
    ("ICICIBANK","ICICI Bank","Financials"),
    ("HINDUNILVR","Hindustan Unilever","Consumer Staples"),
    ("BHARTIARTL","Bharti Airtel","Telecom"),
    ("ITC","ITC Ltd.","Consumer Staples"),
    ("KOTAKBANK","Kotak Mahindra Bank","Financials"),
    ("LT","Larsen & Toubro","Industrials"),
    ("SBIN","State Bank of India","Financials"),
    ("AXISBANK","Axis Bank","Financials"),
    ("BAJFINANCE","Bajaj Finance","Financials"),
    ("SUNPHARMA","Sun Pharmaceutical","Healthcare"),
    ("WIPRO","Wipro Ltd.","Technology"),
    ("TITAN","Titan Company","Consumer Disc."),
    ("ULTRACEMCO","UltraTech Cement","Materials"),
    ("POWERGRID","Power Grid Corp.","Utilities"),
    ("MARUTI","Maruti Suzuki","Consumer Disc."),
    ("HCLTECH","HCL Technologies","Technology"),
    ("ASIANPAINT","Asian Paints","Materials"),
    ("BAJAJFINSV","Bajaj Finserv","Financials"),
    ("NESTLEIND","Nestle India","Consumer Staples"),
    ("TECHM","Tech Mahindra","Technology"),
    ("ONGC","Oil & Natural Gas Corp.","Energy"),
    ("TATAMOTORS","Tata Motors","Consumer Disc."),
    ("HDFCLIFE","HDFC Life Insurance","Financials"),
    ("INDUSINDBK","IndusInd Bank","Financials"),
    ("NTPC","NTPC Ltd.","Utilities"),
    ("DRREDDY","Dr. Reddy's Laboratories","Healthcare"),
    ("M&M","Mahindra & Mahindra","Consumer Disc."),
    ("ADANIPORTS","Adani Ports & SEZ","Industrials"),
    ("BAJAJ-AUTO","Bajaj Auto","Consumer Disc."),
    ("BRITANNIA","Britannia Industries","Consumer Staples"),
    ("CIPLA","Cipla Ltd.","Healthcare"),
    ("COALINDIA","Coal India","Energy"),
    ("DIVISLAB","Divi's Laboratories","Healthcare"),
    ("EICHERMOT","Eicher Motors","Consumer Disc."),
    ("GRASIM","Grasim Industries","Materials"),
    ("HEROMOTOCO","Hero MotoCorp","Consumer Disc."),
    ("HINDALCO","Hindalco Industries","Materials"),
    ("JSWSTEEL","JSW Steel","Materials"),
    ("SBILIFE","SBI Life Insurance","Financials"),
    ("SHREECEM","Shree Cement","Materials"),
    ("TATASTEEL","Tata Steel","Materials"),
    ("TATACONSUM","Tata Consumer Products","Consumer Staples"),
    ("UPL","UPL Ltd.","Materials"),
    ("VEDL","Vedanta Ltd.","Materials"),
    ("APOLLOHOSP","Apollo Hospitals Enterprise","Healthcare"),
    ("BPCL","Bharat Petroleum Corp.","Energy"),
    # Nifty Next 50
    ("ABB","ABB India","Industrials"),
    ("ADANIGREEN","Adani Green Energy","Utilities"),
    ("ADANIENT","Adani Enterprises","Conglomerate"),
    ("AMBUJACEM","Ambuja Cements","Materials"),
    ("AUROPHARMA","Aurobindo Pharma","Healthcare"),
    ("BANDHANBNK","Bandhan Bank","Financials"),
    ("BEL","Bharat Electronics","Industrials"),
    ("BERGEPAINT","Berger Paints India","Materials"),
    ("BIOCON","Biocon Ltd.","Healthcare"),
    ("BOSCHLTD","Bosch Ltd.","Consumer Disc."),
    ("CHOLAFIN","Cholamandalam Investment","Financials"),
    ("DABUR","Dabur India","Consumer Staples"),
    ("DLF","DLF Ltd.","Real Estate"),
    ("FEDERALBNK","Federal Bank","Financials"),
    ("GAIL","GAIL (India)","Energy"),
    ("GODREJCP","Godrej Consumer Products","Consumer Staples"),
    ("HAVELLS","Havells India","Consumer Disc."),
    ("ICICIGI","ICICI Lombard General Insurance","Financials"),
    ("ICICIPRULI","ICICI Prudential Life Insurance","Financials"),
    ("INDUSTOWER","Indus Towers","Telecom"),
    ("IRCTC","Indian Railway Catering & Tourism","Consumer Disc."),
    ("LUPIN","Lupin Ltd.","Healthcare"),
    ("MUTHOOTFIN","Muthoot Finance","Financials"),
    ("NAUKRI","Info Edge (India)","Technology"),
    ("PAGEIND","Page Industries","Consumer Disc."),
    ("PIDILITIND","Pidilite Industries","Materials"),
    ("PNB","Punjab National Bank","Financials"),
    ("RAMCOCEM","Ramco Cements","Materials"),
    ("RECLTD","REC Ltd.","Financials"),
    ("SIEMENS","Siemens India","Industrials"),
    ("TRENT","Trent Ltd.","Consumer Disc."),
    ("TVSMOTOR","TVS Motor Company","Consumer Disc."),
    ("UBL","United Breweries","Consumer Staples"),
    ("VOLTAS","Voltas Ltd.","Consumer Disc."),
    ("ZYDUSLIFE","Zydus Lifesciences","Healthcare"),
    ("ZOMATO","Zomato Ltd.","Consumer Disc."),
    ("PAYTM","One 97 Communications (Paytm)","Technology"),
    ("NYKAA","FSN E-Commerce Ventures (Nykaa)","Consumer Disc."),
    ("POLICYBZR","PB Fintech (PolicyBazaar)","Financials"),
    ("DELHIVERY","Delhivery Ltd.","Industrials"),
    # Nifty Midcap 150
    ("APLAPOLLO","APL Apollo Tubes","Materials"),
    ("ABCAPITAL","Aditya Birla Capital","Financials"),
    ("ABFRL","Aditya Birla Fashion","Consumer Disc."),
    ("ACC","ACC Ltd.","Materials"),
    ("AARTIIND","Aarti Industries","Materials"),
    ("ACMESOLAR","ACME Solar Holdings","Utilities"),
    ("ADANIPOWER","Adani Power","Utilities"),
    ("ADANITRANS","Adani Transmission","Utilities"),
    ("AEGISCHEM","Aegis Chemicals","Materials"),
    ("AJANTPHARM","Ajanta Pharma","Healthcare"),
    ("ALKEM","Alkem Laboratories","Healthcare"),
    ("ALKYLAMINE","Alkyl Amines Chemicals","Materials"),
    ("AMBER","Amber Enterprises India","Consumer Disc."),
    ("AMRINDFIN","AMRI Industries Finance","Financials"),
    ("ANLBEES","Nifty ETF","Financials"),
    ("APARINDS","Apar Industries","Industrials"),
    ("ASTRAZEN","AstraZeneca Pharma India","Healthcare"),
    ("ASTRAL","Astral Ltd.","Materials"),
    ("ATUL","Atul Ltd.","Materials"),
    ("AUBANK","AU Small Finance Bank","Financials"),
    ("BALKRISIND","Balkrishna Industries","Consumer Disc."),
    ("BATAINDIA","Bata India","Consumer Disc."),
    ("BAYERCROP","Bayer CropScience","Materials"),
    ("BBTC","Bombay Burmah Trading","Conglomerate"),
    ("BHARATFORG","Bharat Forge","Industrials"),
    ("BHARATRAS","Bharat Rasayan","Materials"),
    ("BHEL","Bharat Heavy Electricals","Industrials"),
    ("BIKAJI","Bikaji Foods International","Consumer Staples"),
    ("BLUESTARCO","Blue Star Ltd.","Consumer Disc."),
    ("BRIGADE","Brigade Enterprises","Real Estate"),
    ("BSE","BSE Ltd.","Financials"),
    ("CANFINHOME","Can Fin Homes","Financials"),
    ("CANBK","Canara Bank","Financials"),
    ("CARBORUNIV","Carborundum Universal","Materials"),
    ("CASTROLIND","Castrol India","Energy"),
    ("CESC","CESC Ltd.","Utilities"),
    ("CGPOWER","CG Power & Industrial Solutions","Industrials"),
    ("CHAMBLFERT","Chambal Fertilisers","Materials"),
    ("CHEMPLASTS","Chemplast Sanmar","Materials"),
    ("CMSINFO","CMS Info Systems","Technology"),
    ("COFORGE","Coforge Ltd.","Technology"),
    ("COLPAL","Colgate-Palmolive India","Consumer Staples"),
    ("CONCOR","Container Corp. of India","Industrials"),
    ("CRED","CRED (Dreamplug Tech.)","Financials"),
    ("CROMPTON","Crompton Greaves Consumer","Consumer Disc."),
    ("CUMMINSIND","Cummins India","Industrials"),
    ("CYIENT","Cyient Ltd.","Technology"),
    ("DATASTPAT","Data Patterns (India)","Technology"),
    ("DCMSHRIRAM","DCM Shriram","Materials"),
    ("DEEPAKFERT","Deepak Fertilisers","Materials"),
    ("DEEPAKNTR","Deepak Nitrite","Materials"),
    ("DELTACORP","Delta Corp.","Consumer Disc."),
    ("DEVYANI","Devyani International","Consumer Disc."),
    ("DHANI","Dhani Services","Financials"),
    ("DIXON","Dixon Technologies","Technology"),
    ("DMART","Avenue Supermarts (D-Mart)","Consumer Disc."),
    ("ELGIEQUIP","Elgi Equipments","Industrials"),
    ("EMAMILTD","Emami Ltd.","Consumer Staples"),
    ("ENGINERSIN","Engineers India","Industrials"),
    ("EPIGRAL","Epigral Ltd.","Materials"),
    ("EQUITASBNK","Equitas Small Finance Bank","Financials"),
    ("ESCORTS","Escorts Kubota","Consumer Disc."),
    ("EXIDEIND","Exide Industries","Consumer Disc."),
    ("FINEORG","Fine Organic Industries","Materials"),
    ("FINPIPE","Finolex Industries","Materials"),
    ("FLUOROCHEM","Gujarat Fluorochemicals","Materials"),
    ("GICRE","General Insurance Corp.","Financials"),
    ("GILLETTE","Gillette India","Consumer Staples"),
    ("GLAXO","GlaxoSmithKline Pharma","Healthcare"),
    ("GNFC","Gujarat Narmada Valley Fertilizers","Materials"),
    ("GODREJIND","Godrej Industries","Conglomerate"),
    ("GODREJPROP","Godrej Properties","Real Estate"),
    ("GRAPHITE","Graphite India","Materials"),
    ("GREENPANEL","Greenpanel Industries","Materials"),
    ("GRINDWELL","Grindwell Norton","Industrials"),
    ("GSFC","Gujarat State Fertilizers","Materials"),
    ("GSPL","Gujarat State Petronet","Energy"),
    ("GULF OIL","Gulf Oil Lubricants India","Energy"),
    ("HAPPSTMNDS","Happiest Minds Technologies","Technology"),
    ("HATSUN","Hatsun Agro Product","Consumer Staples"),
    ("HFCL","HFCL Ltd.","Telecom"),
    ("HIL","HIL Ltd.","Materials"),
    ("HINDCOPPER","Hindustan Copper","Materials"),
    ("HINDPETRO","Hindustan Petroleum Corp.","Energy"),
    ("HONAUT","Honeywell Automation India","Technology"),
    ("HUDCO","Housing & Urban Dev. Corp.","Financials"),
    ("IBREALEST","Indiabulls Real Estate","Real Estate"),
    ("ICRA","ICRA Ltd.","Financials"),
    ("IDBI","IDBI Bank","Financials"),
    ("IDFC","IDFC Ltd.","Financials"),
    ("IDFCFIRSTB","IDFC First Bank","Financials"),
    ("IEX","Indian Energy Exchange","Financials"),
    ("IGAS","Indraprastha Gas","Energy"),
    ("IIFL","IIFL Finance","Financials"),
    ("IPCALAB","Ipca Laboratories","Healthcare"),
    ("IRB","IRB Infrastructure","Industrials"),
    ("IREDA","Indian Renewable Energy Dev. Agency","Financials"),
    ("IRFC","Indian Railway Finance Corp.","Financials"),
    ("JKCEMENT","JK Cement","Materials"),
    ("JKTYRE","JK Tyre & Industries","Consumer Disc."),
    ("JMFINANCIL","JM Financial","Financials"),
    ("JSL","Jindal Stainless","Materials"),
    ("JUBLFOOD","Jubilant Foodworks","Consumer Disc."),
    ("JUBLINGREA","Jubilant Ingrevia","Materials"),
    ("JUBLPHARMA","Jubilant Pharmova","Healthcare"),
    ("JUSTDIAL","Just Dial","Technology"),
    ("KAJARIACER","Kajaria Ceramics","Materials"),
    ("KALPATPOWR","Kalpataru Power Transmission","Industrials"),
    ("KALYANKJIL","Kalyan Jewellers India","Consumer Disc."),
    ("KANSAINER","Kansai Nerolac Paints","Materials"),
    ("KIRIINDUS","Kiri Industries","Materials"),
    ("KIRLOSBROS","Kirloskar Brothers","Industrials"),
    ("KIRLOSENG","Kirloskar Electric","Industrials"),
    ("KPRMILL","K.P.R. Mill","Consumer Disc."),
    ("KRBL","KRBL Ltd.","Consumer Staples"),
    ("KSB","KSB Ltd.","Industrials"),
    ("LATTEYS","Laxmi Organic Industries","Materials"),
    ("LAURUSLABS","Laurus Labs","Healthcare"),
    ("LEMONTREE","Lemon Tree Hotels","Consumer Disc."),
    ("LINDEINDIA","Linde India","Materials"),
    ("LTIM","LTIMindtree","Technology"),
    ("LTTS","L&T Technology Services","Technology"),
    ("LUXIND","Lux Industries","Consumer Disc."),
    ("MAHABANK","Bank of Maharashtra","Financials"),
    ("MAHINDCIE","Mahindra CIE Automotive","Consumer Disc."),
    ("MAHLIFE","Mahindra Lifespace Dev.","Real Estate"),
    ("MANAPPURAM","Manappuram Finance","Financials"),
    ("MARICO","Marico Ltd.","Consumer Staples"),
    ("MASTEK","Mastek Ltd.","Technology"),
    ("MAXHEALTH","Max Healthcare Institute","Healthcare"),
    ("MCX","Multi Commodity Exchange","Financials"),
    ("MEDANTA","Global Health (Medanta)","Healthcare"),
    ("METROPOLIS","Metropolis Healthcare","Healthcare"),
    ("MFSL","Max Financial Services","Financials"),
    ("MINDTREE","MindTree Ltd.","Technology"),
    ("MMTC","MMTC Ltd.","Conglomerate"),
    ("MOIL","MOIL Ltd.","Materials"),
    ("MRF","MRF Ltd.","Consumer Disc."),
    ("MTAR","MTAR Technologies","Industrials"),
    ("NATCOPHARM","Natco Pharma","Healthcare"),
    ("NESCO","Nesco Ltd.","Real Estate"),
    ("NEULANDLAB","Neuland Laboratories","Healthcare"),
    ("NEWGEN","Newgen Software","Technology"),
    ("NFL","National Fertilizers","Materials"),
    ("NHPC","NHPC Ltd.","Utilities"),
    ("NIACL","New India Assurance","Financials"),
    ("NOCIL","NOCIL Ltd.","Materials"),
    ("NUVOCO","Nuvoco Vistas Corp.","Materials"),
    ("OFSS","Oracle Financial Services","Technology"),
    ("OIL","Oil India Ltd.","Energy"),
    ("OLECTRA","Olectra Greentech","Consumer Disc."),
    ("ORIENTELEC","Orient Electric","Consumer Disc."),
    ("PGHH","Procter & Gamble Hygiene","Consumer Staples"),
    ("PHOENIXLTD","Phoenix Mills","Real Estate"),
    ("POLYCAB","Polycab India","Industrials"),
    ("POLYMED","Poly Medicure","Healthcare"),
    ("PRAJIND","Praj Industries","Industrials"),
    ("PRESTIGE","Prestige Estates Projects","Real Estate"),
    ("PRINCEPIPE","Prince Pipes and Fittings","Materials"),
    ("PRSMJOHNSN","Prism Johnson","Materials"),
    ("PTC","PTC India","Energy"),
    ("PVRINOX","PVR INOX","Consumer Disc."),
    ("RADICO","Radico Khaitan","Consumer Staples"),
    ("RAILTEL","RailTel Corp. of India","Technology"),
    ("RAINBOW","Rainbow Children's Medicare","Healthcare"),
    ("RAJESHEXPO","Rajesh Exports","Consumer Disc."),
    ("RALLIS","Rallis India","Materials"),
    ("RATNAMANI","Ratnamani Metals","Industrials"),
    ("RAYMOND","Raymond Ltd.","Consumer Disc."),
    ("RITES","RITES Ltd.","Industrials"),
    ("ROUTE","Route Mobile","Technology"),
    ("SAIL","Steel Authority of India","Materials"),
    ("SANDHAR","Sandhar Technologies","Consumer Disc."),
    ("SCHAEFFLER","Schaeffler India","Consumer Disc."),
    ("SEQUENT","Sequent Scientific","Healthcare"),
    ("SHILPAMED","Shilpa Medicare","Healthcare"),
    ("SHYAMMETL","Shyam Metalics","Materials"),
    ("SJVN","SJVN Ltd.","Utilities"),
    ("SKFINDIA","SKF India","Industrials"),
    ("SOBHA","Sobha Ltd.","Real Estate"),
    ("SPARC","Sun Pharma Advanced Research","Healthcare"),
    ("SPENCERS","Spencer's Retail","Consumer Disc."),
    ("STER","Sterlite Technologies","Technology"),
    ("SUPPETRO","Supreme Petrochem","Materials"),
    ("SUPREMEIND","Supreme Industries","Materials"),
    ("SUVENPHAR","Suven Pharmaceuticals","Healthcare"),
    ("SYNGENE","Syngene International","Healthcare"),
    ("TANLA","Tanla Platforms","Technology"),
    ("TATACHEM","Tata Chemicals","Materials"),
    ("TATACOMM","Tata Communications","Telecom"),
    ("TATAELXSI","Tata Elxsi","Technology"),
    ("TATAINVEST","Tata Investment Corp.","Financials"),
    ("TATAPOWER","Tata Power Co.","Utilities"),
    ("TATVA","Tatva Chintan Pharma","Materials"),
    ("THERMAX","Thermax Ltd.","Industrials"),
    ("TIMKEN","Timken India","Industrials"),
    ("TIMETECHNO","Time Technoplast","Materials"),
    ("TINPLATE","Tinplate Co. of India","Materials"),
    ("TORNTPHARM","Torrent Pharmaceuticals","Healthcare"),
    ("TORNTPOWER","Torrent Power","Utilities"),
    ("TRIL","Tcns Clothing Co.","Consumer Disc."),
    ("TRIVENI","Triveni Engineering","Consumer Staples"),
    ("UCOBANK","UCO Bank","Financials"),
    ("UNIONBANK","Union Bank of India","Financials"),
    ("UNITDSPR","United Spirits","Consumer Staples"),
    ("UTIAMC","UTI Asset Management","Financials"),
    ("VAIBHAVGBL","Vaibhav Global","Consumer Disc."),
    ("VARDHACRLC","Vardhman Acrylics","Materials"),
    ("VARROC","Varroc Engineering","Consumer Disc."),
    ("VGUARD","V-Guard Industries","Consumer Disc."),
    ("VINATIORGA","Vinati Organics","Materials"),
    ("VIPIND","VIP Industries","Consumer Disc."),
    ("VMART","V-Mart Retail","Consumer Disc."),
    ("VSTIND","VST Industries","Consumer Staples"),
    ("WABCOINDIA","Wabco India","Consumer Disc."),
    ("WELCORP","Welspun Corp.","Materials"),
    ("WELSPUNIND","Welspun India","Consumer Disc."),
    ("WESTLIFE","Westlife Foodworld","Consumer Disc."),
    ("WHIRLPOOL","Whirlpool of India","Consumer Disc."),
    ("WIPRO","Wipro Ltd.","Technology"),
    ("XCHANGING","Xchanging Solutions","Technology"),
    ("YESBANK","Yes Bank","Financials"),
    ("ZEEL","Zee Entertainment Enterprises","Communication"),
    ("ZENTEC","Zen Technologies","Industrials"),
    ("ZENSARTECH","Zensar Technologies","Technology"),
]

def india_entry(symbol, name, sector):
    return {
        "symbol": symbol, "name": name,
        "yahooSuffix": f"{symbol}.NS",
        "tvSymbol": f"NSE:{symbol}",
        "sector": sector,
    }

def build_india():
    seen = set()
    out = []
    for row in INDIA_RAW:
        sym = row[0]
        if sym not in seen:
            seen.add(sym)
            out.append(india_entry(*row))
    return out

# ── UAE: DFM + ADX ───────────────────────────────────────────────────────────
UAE_TICKERS = [
    # ADX
    {"symbol":"FAB","name":"First Abu Dhabi Bank","yahooSuffix":"FAB.AD","tvSymbol":"ADX:FAB","sector":"Financials"},
    {"symbol":"ADCB","name":"Abu Dhabi Commercial Bank","yahooSuffix":"ADCB.AD","tvSymbol":"ADX:ADCB","sector":"Financials"},
    {"symbol":"IHC","name":"International Holding Co.","yahooSuffix":"IHC.AD","tvSymbol":"ADX:IHC","sector":"Conglomerate"},
    {"symbol":"ADNOCDIST","name":"ADNOC Distribution","yahooSuffix":"ADNOCDIST.AD","tvSymbol":"ADX:ADNOCDIST","sector":"Energy"},
    {"symbol":"ETISALAT","name":"e& (Etisalat)","yahooSuffix":"ETISALAT.AD","tvSymbol":"ADX:ETISALAT","sector":"Telecom"},
    {"symbol":"ALDAR","name":"Aldar Properties","yahooSuffix":"ALDAR.AD","tvSymbol":"ADX:ALDAR","sector":"Real Estate"},
    {"symbol":"TAQA","name":"Abu Dhabi National Energy","yahooSuffix":"TAQA.AD","tvSymbol":"ADX:TAQA","sector":"Utilities"},
    {"symbol":"FERTIGLOBE","name":"Fertiglobe","yahooSuffix":"FERTIGLOBE.AD","tvSymbol":"ADX:FERTIGLOBE","sector":"Materials"},
    {"symbol":"NMDC","name":"National Marine Dredging","yahooSuffix":"NMDC.AD","tvSymbol":"ADX:NMDC","sector":"Industrials"},
    {"symbol":"ALPHADHABI","name":"Alpha Dhabi Holding","yahooSuffix":"ALPHADHABI.AD","tvSymbol":"ADX:ALPHADHABI","sector":"Conglomerate"},
    {"symbol":"ADIB","name":"Abu Dhabi Islamic Bank","yahooSuffix":"ADIB.AD","tvSymbol":"ADX:ADIB","sector":"Financials"},
    {"symbol":"ADNOCDRILLING","name":"ADNOC Drilling","yahooSuffix":"ADNOCDRILLING.AD","tvSymbol":"ADX:ADNOCDRILLING","sector":"Energy"},
    {"symbol":"ADPORTS","name":"AD Ports Group","yahooSuffix":"ADPORTS.AD","tvSymbol":"ADX:ADPORTS","sector":"Industrials"},
    {"symbol":"WAHA","name":"Waha Capital","yahooSuffix":"WAHA.AD","tvSymbol":"ADX:WAHA","sector":"Financials"},
    {"symbol":"AGTHIA","name":"Agthia Group","yahooSuffix":"AGTHIA.AD","tvSymbol":"ADX:AGTHIA","sector":"Consumer Staples"},
    {"symbol":"ALICO","name":"Abu Dhabi National Insurance","yahooSuffix":"ALICO.AD","tvSymbol":"ADX:ALICO","sector":"Financials"},
    {"symbol":"ADNH","name":"Abu Dhabi National Hotels","yahooSuffix":"ADNH.AD","tvSymbol":"ADX:ADNH","sector":"Consumer Disc."},
    {"symbol":"RAKCC","name":"RAK Ceramics","yahooSuffix":"RAKCC.AD","tvSymbol":"ADX:RAKCC","sector":"Materials"},
    {"symbol":"PUREHEALTH","name":"Pure Health Holding","yahooSuffix":"PUREHEALTH.AD","tvSymbol":"ADX:PUREHEALTH","sector":"Healthcare"},
    {"symbol":"MULTIPLY","name":"Multiply Group","yahooSuffix":"MULTIPLY.AD","tvSymbol":"ADX:MULTIPLY","sector":"Technology"},
    {"symbol":"ESHRAQ","name":"Eshraq Investments","yahooSuffix":"ESHRAQ.AD","tvSymbol":"ADX:ESHRAQ","sector":"Real Estate"},
    {"symbol":"INVEST","name":"Abu Dhabi Investment Co.","yahooSuffix":"INVEST.AD","tvSymbol":"ADX:INVEST","sector":"Financials"},
    {"symbol":"RAK","name":"RAK Properties","yahooSuffix":"RAK.AD","tvSymbol":"ADX:RAK","sector":"Real Estate"},
    {"symbol":"GHITHA","name":"Ghitha Holding","yahooSuffix":"GHITHA.AD","tvSymbol":"ADX:GHITHA","sector":"Consumer Staples"},
    {"symbol":"FOODCO","name":"Foodco Holding","yahooSuffix":"FOODCO.AD","tvSymbol":"ADX:FOODCO","sector":"Consumer Staples"},
    {"symbol":"MANAZEL","name":"Manazel Real Estate","yahooSuffix":"MANAZEL.AD","tvSymbol":"ADX:MANAZEL","sector":"Real Estate"},
    {"symbol":"NBAD","name":"National Corp. for Tourism","yahooSuffix":"NBAD.AD","tvSymbol":"ADX:NBAD","sector":"Consumer Disc."},
    {"symbol":"ADNOC","name":"ADNOC Gas","yahooSuffix":"ADNOCGAS.AD","tvSymbol":"ADX:ADNOCGAS","sector":"Energy"},
    {"symbol":"BOINVEST","name":"Bank of Investments","yahooSuffix":"BOINVEST.AD","tvSymbol":"ADX:BOINVEST","sector":"Financials"},
    {"symbol":"NAQAAINT","name":"Naqaa International","yahooSuffix":"NAQAAINT.AD","tvSymbol":"ADX:NAQAAINT","sector":"Utilities"},
    # DFM
    {"symbol":"EMAAR","name":"Emaar Properties","yahooSuffix":"EMAAR.DU","tvSymbol":"DFM:EMAAR","sector":"Real Estate"},
    {"symbol":"DIB","name":"Dubai Islamic Bank","yahooSuffix":"DIB.DU","tvSymbol":"DFM:DIB","sector":"Financials"},
    {"symbol":"ENBD","name":"Emirates NBD","yahooSuffix":"ENBD.DU","tvSymbol":"DFM:ENBD","sector":"Financials"},
    {"symbol":"DEWA","name":"Dubai Electricity & Water Authority","yahooSuffix":"DEWA.DU","tvSymbol":"DFM:DEWA","sector":"Utilities"},
    {"symbol":"AIRARABIA","name":"Air Arabia","yahooSuffix":"AIRARABIA.DU","tvSymbol":"DFM:AIRARABIA","sector":"Industrials"},
    {"symbol":"DU","name":"Emirates Integrated Telecom","yahooSuffix":"DU.DU","tvSymbol":"DFM:DU","sector":"Telecom"},
    {"symbol":"SALIK","name":"Salik Co.","yahooSuffix":"SALIK.DU","tvSymbol":"DFM:SALIK","sector":"Industrials"},
    {"symbol":"DEYAAR","name":"Deyaar Development","yahooSuffix":"DEYAAR.DU","tvSymbol":"DFM:DEYAAR","sector":"Real Estate"},
    {"symbol":"AMANAT","name":"Amanat Holdings","yahooSuffix":"AMANAT.DU","tvSymbol":"DFM:AMANAT","sector":"Financials"},
    {"symbol":"GULFINV","name":"Gulf Investment Corp.","yahooSuffix":"GULFINV.DU","tvSymbol":"DFM:GULFINV","sector":"Financials"},
    {"symbol":"EMAARDEV","name":"Emaar Development","yahooSuffix":"EMAARDEV.DU","tvSymbol":"DFM:EMAARDEV","sector":"Real Estate"},
    {"symbol":"ARAMEX","name":"Aramex PJSC","yahooSuffix":"ARAMEX.DU","tvSymbol":"DFM:ARAMEX","sector":"Industrials"},
    {"symbol":"DUBAI","name":"Dubai Investments","yahooSuffix":"DUBAI.DU","tvSymbol":"DFM:DUBAI","sector":"Financials"},
    {"symbol":"GFH","name":"GFH Financial Group","yahooSuffix":"GFH.DU","tvSymbol":"DFM:GFH","sector":"Financials"},
    {"symbol":"UNION","name":"Union Properties","yahooSuffix":"UNION.DU","tvSymbol":"DFM:UNION","sector":"Real Estate"},
    {"symbol":"DFM","name":"Dubai Financial Market","yahooSuffix":"DFM.DU","tvSymbol":"DFM:DFM","sector":"Financials"},
    {"symbol":"TECOM","name":"TECOM Group","yahooSuffix":"TECOM.DU","tvSymbol":"DFM:TECOM","sector":"Real Estate"},
    {"symbol":"TABREED","name":"National Central Cooling (Tabreed)","yahooSuffix":"TABREED.DU","tvSymbol":"DFM:TABREED","sector":"Utilities"},
    {"symbol":"SHUAA","name":"Shuaa Capital","yahooSuffix":"SHUAA.DU","tvSymbol":"DFM:SHUAA","sector":"Financials"},
    {"symbol":"SALAMA","name":"Islamic Arab Insurance (Salama)","yahooSuffix":"SALAMA.DU","tvSymbol":"DFM:SALAMA","sector":"Financials"},
    {"symbol":"AMLAK","name":"Amlak Finance","yahooSuffix":"AMLAK.DU","tvSymbol":"DFM:AMLAK","sector":"Financials"},
    {"symbol":"EIC","name":"Emirates Insurance Co.","yahooSuffix":"EIC.DU","tvSymbol":"DFM:EIC","sector":"Financials"},
    {"symbol":"DHS","name":"Dubai Refreshments","yahooSuffix":"DHS.DU","tvSymbol":"DFM:DHS","sector":"Consumer Staples"},
    {"symbol":"NNAC","name":"National Cement Co. (Dubai)","yahooSuffix":"NNAC.DU","tvSymbol":"DFM:NNAC","sector":"Materials"},
    {"symbol":"EMFDII","name":"Emirates Financial Services","yahooSuffix":"EMFD.DU","tvSymbol":"DFM:EMFD","sector":"Financials"},
    {"symbol":"NASR","name":"Ajman Bank","yahooSuffix":"NASR.DU","tvSymbol":"DFM:NASR","sector":"Financials"},
    {"symbol":"EKTITAB","name":"Ektitab Holding","yahooSuffix":"EKTITAB.DU","tvSymbol":"DFM:EKTITAB","sector":"Financials"},
]

# ── Saudi Arabia: Full TASI ──────────────────────────────────────────────────
SAUDI_TICKERS = [
    # Energy
    {"symbol":"2222","name":"Saudi Aramco","yahooSuffix":"2222.SR","tvSymbol":"TADAWUL:2222","sector":"Energy"},
    {"symbol":"2380","name":"Petro Rabigh","yahooSuffix":"2380.SR","tvSymbol":"TADAWUL:2380","sector":"Energy"},
    {"symbol":"9201","name":"Saudi Aramco Base Oil (Luberef)","yahooSuffix":"9201.SR","tvSymbol":"TADAWUL:9201","sector":"Energy"},
    {"symbol":"2346","name":"Saudi Aramco Total Refining (SATORP ref.)","yahooSuffix":"2346.SR","tvSymbol":"TADAWUL:2346","sector":"Energy"},
    {"symbol":"2030","name":"Saudi Arabian Mining (Maaden) ref.","yahooSuffix":"2030.SR","tvSymbol":"TADAWUL:2030","sector":"Materials"},
    # Materials / Petrochemicals
    {"symbol":"2010","name":"SABIC","yahooSuffix":"2010.SR","tvSymbol":"TADAWUL:2010","sector":"Materials"},
    {"symbol":"1211","name":"Ma'aden","yahooSuffix":"1211.SR","tvSymbol":"TADAWUL:1211","sector":"Materials"},
    {"symbol":"4030","name":"SAFCO (Saudi Arabian Fertilizer)","yahooSuffix":"4030.SR","tvSymbol":"TADAWUL:4030","sector":"Materials"},
    {"symbol":"2060","name":"Saudi Kayan Petrochemical","yahooSuffix":"2060.SR","tvSymbol":"TADAWUL:2060","sector":"Materials"},
    {"symbol":"2001","name":"Advanced Petrochemical","yahooSuffix":"2001.SR","tvSymbol":"TADAWUL:2001","sector":"Materials"},
    {"symbol":"2290","name":"Yanbu National Petrochem (Yansab)","yahooSuffix":"2290.SR","tvSymbol":"TADAWUL:2290","sector":"Materials"},
    {"symbol":"2300","name":"Saudi Industrial Investment Group","yahooSuffix":"2300.SR","tvSymbol":"TADAWUL:2300","sector":"Materials"},
    {"symbol":"2310","name":"Sipchem","yahooSuffix":"2310.SR","tvSymbol":"TADAWUL:2310","sector":"Materials"},
    {"symbol":"4140","name":"National Petrochemical","yahooSuffix":"4140.SR","tvSymbol":"TADAWUL:4140","sector":"Materials"},
    {"symbol":"2090","name":"National Industrialization (Tasnee)","yahooSuffix":"2090.SR","tvSymbol":"TADAWUL:2090","sector":"Materials"},
    {"symbol":"2200","name":"Arabian Cement","yahooSuffix":"2200.SR","tvSymbol":"TADAWUL:2200","sector":"Materials"},
    {"symbol":"2210","name":"Saudi Cement","yahooSuffix":"2210.SR","tvSymbol":"TADAWUL:2210","sector":"Materials"},
    {"symbol":"2220","name":"Yanbu Cement","yahooSuffix":"2220.SR","tvSymbol":"TADAWUL:2220","sector":"Materials"},
    {"symbol":"2230","name":"Eastern Province Cement","yahooSuffix":"2230.SR","tvSymbol":"TADAWUL:2230","sector":"Materials"},
    {"symbol":"2240","name":"Qassim Cement","yahooSuffix":"2240.SR","tvSymbol":"TADAWUL:2240","sector":"Materials"},
    {"symbol":"2250","name":"Saudi Ceramic","yahooSuffix":"2250.SR","tvSymbol":"TADAWUL:2250","sector":"Materials"},
    {"symbol":"2320","name":"Al Yamamah Steel Industries","yahooSuffix":"2320.SR","tvSymbol":"TADAWUL:2320","sector":"Materials"},
    {"symbol":"2360","name":"National Metal Manufacturing & Casting","yahooSuffix":"2360.SR","tvSymbol":"TADAWUL:2360","sector":"Materials"},
    {"symbol":"3001","name":"Red Sea International","yahooSuffix":"3001.SR","tvSymbol":"TADAWUL:3001","sector":"Industrials"},
    {"symbol":"3002","name":"United Wire Factories","yahooSuffix":"3002.SR","tvSymbol":"TADAWUL:3002","sector":"Materials"},
    {"symbol":"3003","name":"Saudi Building Systems","yahooSuffix":"3003.SR","tvSymbol":"TADAWUL:3003","sector":"Materials"},
    {"symbol":"2150","name":"Saudi Paper Group","yahooSuffix":"2150.SR","tvSymbol":"TADAWUL:2150","sector":"Materials"},
    {"symbol":"2160","name":"Electrical Industries Co.","yahooSuffix":"2160.SR","tvSymbol":"TADAWUL:2160","sector":"Industrials"},
    {"symbol":"2170","name":"Saudi Cable Co.","yahooSuffix":"2170.SR","tvSymbol":"TADAWUL:2170","sector":"Industrials"},
    {"symbol":"2110","name":"Zamil Industrial Investment","yahooSuffix":"2110.SR","tvSymbol":"TADAWUL:2110","sector":"Industrials"},
    # Financials / Banks
    {"symbol":"1120","name":"Al Rajhi Bank","yahooSuffix":"1120.SR","tvSymbol":"TADAWUL:1120","sector":"Financials"},
    {"symbol":"1180","name":"Saudi National Bank","yahooSuffix":"1180.SR","tvSymbol":"TADAWUL:1180","sector":"Financials"},
    {"symbol":"1010","name":"Alinma Bank","yahooSuffix":"1010.SR","tvSymbol":"TADAWUL:1010","sector":"Financials"},
    {"symbol":"1050","name":"Banque Saudi Fransi","yahooSuffix":"1050.SR","tvSymbol":"TADAWUL:1050","sector":"Financials"},
    {"symbol":"1060","name":"Saudi Investment Bank","yahooSuffix":"1060.SR","tvSymbol":"TADAWUL:1060","sector":"Financials"},
    {"symbol":"1080","name":"Arab National Bank","yahooSuffix":"1080.SR","tvSymbol":"TADAWUL:1080","sector":"Financials"},
    {"symbol":"1140","name":"Al-Awwal Bank","yahooSuffix":"1140.SR","tvSymbol":"TADAWUL:1140","sector":"Financials"},
    {"symbol":"1150","name":"Riyad Bank","yahooSuffix":"1150.SR","tvSymbol":"TADAWUL:1150","sector":"Financials"},
    {"symbol":"1020","name":"Bank AlJazira","yahooSuffix":"1020.SR","tvSymbol":"TADAWUL:1020","sector":"Financials"},
    {"symbol":"1030","name":"Saudi Finance (AMLAK)","yahooSuffix":"1030.SR","tvSymbol":"TADAWUL:1030","sector":"Financials"},
    {"symbol":"1201","name":"Tawuniya (Company for Cooperative Insurance)","yahooSuffix":"1201.SR","tvSymbol":"TADAWUL:1201","sector":"Financials"},
    {"symbol":"1202","name":"Gulf International Bank","yahooSuffix":"1202.SR","tvSymbol":"TADAWUL:1202","sector":"Financials"},
    {"symbol":"4280","name":"Saudi Tadawul Group","yahooSuffix":"4280.SR","tvSymbol":"TADAWUL:4280","sector":"Financials"},
    {"symbol":"8200","name":"Bupa Arabia for Cooperative Insurance","yahooSuffix":"8200.SR","tvSymbol":"TADAWUL:8200","sector":"Healthcare"},
    {"symbol":"8210","name":"Walaa Cooperative Insurance","yahooSuffix":"8210.SR","tvSymbol":"TADAWUL:8210","sector":"Financials"},
    {"symbol":"8260","name":"Saudi Reinsurance Co.","yahooSuffix":"8260.SR","tvSymbol":"TADAWUL:8260","sector":"Financials"},
    {"symbol":"8300","name":"Mediterranean & Gulf Insurance","yahooSuffix":"8300.SR","tvSymbol":"TADAWUL:8300","sector":"Financials"},
    {"symbol":"8310","name":"Arabia Insurance Cooperative","yahooSuffix":"8310.SR","tvSymbol":"TADAWUL:8310","sector":"Financials"},
    # Telecom
    {"symbol":"2350","name":"Saudi Telecom (STC)","yahooSuffix":"2350.SR","tvSymbol":"TADAWUL:2350","sector":"Telecom"},
    {"symbol":"7010","name":"Mobily (Etihad Etisalat)","yahooSuffix":"7010.SR","tvSymbol":"TADAWUL:7010","sector":"Telecom"},
    {"symbol":"7020","name":"Zain KSA","yahooSuffix":"7020.SR","tvSymbol":"TADAWUL:7020","sector":"Telecom"},
    # Utilities
    {"symbol":"6010","name":"Saudi Electricity Co.","yahooSuffix":"6010.SR","tvSymbol":"TADAWUL:6010","sector":"Utilities"},
    {"symbol":"2082","name":"ACWA Power","yahooSuffix":"2082.SR","tvSymbol":"TADAWUL:2082","sector":"Utilities"},
    {"symbol":"6090","name":"Marafiq (Power & Water Utility)","yahooSuffix":"6090.SR","tvSymbol":"TADAWUL:6090","sector":"Utilities"},
    {"symbol":"4080","name":"Saudi Gas Company","yahooSuffix":"4080.SR","tvSymbol":"TADAWUL:4080","sector":"Utilities"},
    # Consumer Staples
    {"symbol":"4200","name":"Al Marai","yahooSuffix":"4200.SR","tvSymbol":"TADAWUL:4200","sector":"Consumer Staples"},
    {"symbol":"2050","name":"Savola Group","yahooSuffix":"2050.SR","tvSymbol":"TADAWUL:2050","sector":"Consumer Staples"},
    {"symbol":"4001","name":"NADEC","yahooSuffix":"4001.SR","tvSymbol":"TADAWUL:4001","sector":"Consumer Staples"},
    {"symbol":"4002","name":"Al-Jouf Agriculture Development","yahooSuffix":"4002.SR","tvSymbol":"TADAWUL:4002","sector":"Consumer Staples"},
    {"symbol":"4003","name":"Saudi Agricultural & Livestock","yahooSuffix":"4003.SR","tvSymbol":"TADAWUL:4003","sector":"Consumer Staples"},
    {"symbol":"4161","name":"Almunajem Foods","yahooSuffix":"4161.SR","tvSymbol":"TADAWUL:4161","sector":"Consumer Staples"},
    {"symbol":"6001","name":"Halwani Bros.","yahooSuffix":"6001.SR","tvSymbol":"TADAWUL:6001","sector":"Consumer Staples"},
    {"symbol":"4110","name":"Alyasra Food","yahooSuffix":"4110.SR","tvSymbol":"TADAWUL:4110","sector":"Consumer Staples"},
    # Consumer Discretionary
    {"symbol":"4190","name":"Jarir Marketing","yahooSuffix":"4190.SR","tvSymbol":"TADAWUL:4190","sector":"Consumer Disc."},
    {"symbol":"4240","name":"Fawaz Abdulaziz Alhokair","yahooSuffix":"4240.SR","tvSymbol":"TADAWUL:4240","sector":"Consumer Disc."},
    {"symbol":"4170","name":"Al-Othaim Markets","yahooSuffix":"4170.SR","tvSymbol":"TADAWUL:4170","sector":"Consumer Disc."},
    {"symbol":"4180","name":"Bindawood Holding","yahooSuffix":"4180.SR","tvSymbol":"TADAWUL:4180","sector":"Consumer Disc."},
    {"symbol":"4250","name":"SACO (Saudi Home Improvement)","yahooSuffix":"4250.SR","tvSymbol":"TADAWUL:4250","sector":"Consumer Disc."},
    {"symbol":"4090","name":"SASCO","yahooSuffix":"4090.SR","tvSymbol":"TADAWUL:4090","sector":"Consumer Disc."},
    {"symbol":"4040","name":"Saudi Automotive Services","yahooSuffix":"4040.SR","tvSymbol":"TADAWUL:4040","sector":"Consumer Disc."},
    {"symbol":"4100","name":"Saudi Hotels & Resorts Areas","yahooSuffix":"4100.SR","tvSymbol":"TADAWUL:4100","sector":"Consumer Disc."},
    # Healthcare
    {"symbol":"2280","name":"Bupa Arabia","yahooSuffix":"2280.SR","tvSymbol":"TADAWUL:2280","sector":"Healthcare"},
    {"symbol":"4017","name":"Aldawaa Medical Services","yahooSuffix":"4017.SR","tvSymbol":"TADAWUL:4017","sector":"Healthcare"},
    {"symbol":"4013","name":"Saudi Pharmaceutical Industries","yahooSuffix":"4013.SR","tvSymbol":"TADAWUL:4013","sector":"Healthcare"},
    {"symbol":"4009","name":"SPIMACO Addwaeih","yahooSuffix":"4009.SR","tvSymbol":"TADAWUL:4009","sector":"Healthcare"},
    {"symbol":"4005","name":"Al Hammadi Co. for Development","yahooSuffix":"4005.SR","tvSymbol":"TADAWUL:4005","sector":"Healthcare"},
    {"symbol":"4016","name":"Dallah Healthcare","yahooSuffix":"4016.SR","tvSymbol":"TADAWUL:4016","sector":"Healthcare"},
    {"symbol":"4160","name":"Mouwasat Medical Services","yahooSuffix":"4160.SR","tvSymbol":"TADAWUL:4160","sector":"Healthcare"},
    {"symbol":"4264","name":"Nahdi Medical Co.","yahooSuffix":"4264.SR","tvSymbol":"TADAWUL:4264","sector":"Healthcare"},
    {"symbol":"4014","name":"Middle East Healthcare (MEAHCO)","yahooSuffix":"4014.SR","tvSymbol":"TADAWUL:4014","sector":"Healthcare"},
    {"symbol":"4007","name":"Medical Elements Co.","yahooSuffix":"4007.SR","tvSymbol":"TADAWUL:4007","sector":"Healthcare"},
    # Real Estate
    {"symbol":"4320","name":"Emaar The Economic City","yahooSuffix":"4320.SR","tvSymbol":"TADAWUL:4320","sector":"Real Estate"},
    {"symbol":"4300","name":"Dar Al Arkan Real Estate","yahooSuffix":"4300.SR","tvSymbol":"TADAWUL:4300","sector":"Real Estate"},
    {"symbol":"4310","name":"Kingdom Holding Co.","yahooSuffix":"4310.SR","tvSymbol":"TADAWUL:4310","sector":"Conglomerate"},
    {"symbol":"4220","name":"Arriyadh Development","yahooSuffix":"4220.SR","tvSymbol":"TADAWUL:4220","sector":"Real Estate"},
    {"symbol":"4330","name":"Saudi Real Estate Co.","yahooSuffix":"4330.SR","tvSymbol":"TADAWUL:4330","sector":"Real Estate"},
    {"symbol":"4344","name":"Retal Urban Development","yahooSuffix":"4344.SR","tvSymbol":"TADAWUL:4344","sector":"Real Estate"},
    {"symbol":"4345","name":"ROSHN Real Estate","yahooSuffix":"4345.SR","tvSymbol":"TADAWUL:4345","sector":"Real Estate"},
    {"symbol":"4070","name":"Al-Ahsa Development Co.","yahooSuffix":"4070.SR","tvSymbol":"TADAWUL:4070","sector":"Real Estate"},
    # Industrials / Construction
    {"symbol":"1303","name":"Rawabi Holding","yahooSuffix":"1303.SR","tvSymbol":"TADAWUL:1303","sector":"Industrials"},
    {"symbol":"1301","name":"Astra Industrial Group","yahooSuffix":"1301.SR","tvSymbol":"TADAWUL:1301","sector":"Industrials"},
    {"symbol":"4130","name":"Abdullah Al Khodari Sons","yahooSuffix":"4130.SR","tvSymbol":"TADAWUL:4130","sector":"Industrials"},
    {"symbol":"4150","name":"Aseer Trading & Tourism","yahooSuffix":"4150.SR","tvSymbol":"TADAWUL:4150","sector":"Industrials"},
    {"symbol":"2130","name":"Saudi Industrial Services","yahooSuffix":"2130.SR","tvSymbol":"TADAWUL:2130","sector":"Industrials"},
    {"symbol":"2110","name":"Zamil Industrial Investment","yahooSuffix":"2110.SR","tvSymbol":"TADAWUL:2110","sector":"Industrials"},
    {"symbol":"4050","name":"Saudi Printing & Packaging","yahooSuffix":"4050.SR","tvSymbol":"TADAWUL:4050","sector":"Industrials"},
    {"symbol":"2370","name":"Middle East Specialized Cables","yahooSuffix":"2370.SR","tvSymbol":"TADAWUL:2370","sector":"Industrials"},
    {"symbol":"9202","name":"Lumi Rental Co.","yahooSuffix":"9202.SR","tvSymbol":"TADAWUL:9202","sector":"Industrials"},
    {"symbol":"9203","name":"Theeb Rent a Car","yahooSuffix":"9203.SR","tvSymbol":"TADAWUL:9203","sector":"Industrials"},
    # Technology
    {"symbol":"9200","name":"Elm Co.","yahooSuffix":"9200.SR","tvSymbol":"TADAWUL:9200","sector":"Technology"},
    {"symbol":"9204","name":"Al Moammar Information Systems","yahooSuffix":"9204.SR","tvSymbol":"TADAWUL:9204","sector":"Technology"},
    {"symbol":"5110","name":"STC Solutions","yahooSuffix":"5110.SR","tvSymbol":"TADAWUL:5110","sector":"Technology"},
]

def build_uae():
    seen = set()
    out = []
    for t in UAE_TICKERS:
        if t["symbol"] not in seen:
            seen.add(t["symbol"])
            out.append(t)
    return out

def build_saudi():
    seen = set()
    out = []
    for t in SAUDI_TICKERS:
        if t["symbol"] not in seen:
            seen.add(t["symbol"])
            out.append(t)
    return out

def main():
    out_path = Path(__file__).parent.parent / "data" / "watchlist.json"

    us = build_us()
    india = build_india()
    uae = build_uae()
    saudi = build_saudi()

    watchlist = {
        "US": {
            "description": "S&P 500 + Nasdaq 100 (full constituent lists, deduped)",
            "tickers": us,
        },
        "India": {
            "description": "Nifty 500 — NSE India (Nifty 50 + Next 50 + Midcap 150 + Smallcap 250)",
            "tickers": india,
        },
        "UAE": {
            "description": "DFM (Dubai Financial Market) + ADX (Abu Dhabi Securities Exchange)",
            "tickers": uae,
        },
        "Saudi": {
            "description": "Tadawul All Share Index (TASI) — full list",
            "tickers": saudi,
        },
    }

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(watchlist, f, indent=2, ensure_ascii=False)

    print(f"US:    {len(us)}")
    print(f"India: {len(india)}")
    print(f"UAE:   {len(uae)}")
    print(f"Saudi: {len(saudi)}")
    print(f"Total: {len(us)+len(india)+len(uae)+len(saudi)}")
    print(f"Written to {out_path}")

if __name__ == "__main__":
    main()
