"""Tests for the B1 typed, validated configuration layer.

``tradingagents/config_schema.py`` is additive — the dict remains the
runtime currency everywhere; this module only adds validation (warn-only
by default, strict via ``config["strict_config"]`` /
``TRADINGAGENTS_STRICT_CONFIG``) and an autogenerated
``docs/CONFIG_REFERENCE.md``. See docs/CORE_FEATURES_PLAN.md F5.
"""

from __future__ import annotations

import pytest

from tradingagents.config_schema import (
    ConfigValidationError,
    TradingAgentsConfig,
    generate_config_reference_markdown,
    validate_config,
)
from tradingagents.default_config import DEFAULT_CONFIG


@pytest.mark.unit
class TestEveryDefaultConfigKeyRoundTrips:
    """The regression this whole module exists to prevent: a key drifts
    out of sync between DEFAULT_CONFIG and the schema."""

    def test_default_config_validates_with_no_errors(self):
        issues = validate_config(DEFAULT_CONFIG)
        errors = [i for i in issues if i.severity == "error"]
        assert errors == [], f"DEFAULT_CONFIG fails schema validation: {errors}"

    def test_default_config_has_no_unrecognized_keys(self):
        issues = validate_config(DEFAULT_CONFIG)
        warnings = [i for i in issues if i.severity == "warning"]
        assert warnings == [], f"DEFAULT_CONFIG has keys missing from the schema: {warnings}"

    def test_every_default_config_key_is_a_schema_field(self):
        schema_fields = set(TradingAgentsConfig.model_fields)
        missing = set(DEFAULT_CONFIG) - schema_fields
        assert not missing, f"DEFAULT_CONFIG keys with no TradingAgentsConfig field: {missing}"

    def test_model_validate_accepts_the_full_default_config(self):
        # Exercises pydantic directly (not just validate_config's wrapper).
        TradingAgentsConfig.model_validate(DEFAULT_CONFIG)


@pytest.mark.unit
class TestUnknownKeyDetection:
    def test_unknown_key_produces_warning_not_error(self):
        issues = validate_config({"llm_provider": "google", "totally_made_up_key": 1})
        assert len(issues) == 1
        assert issues[0].severity == "warning"
        assert "totally_made_up_key" in issues[0].message

    def test_typo_suggests_closest_known_key(self):
        issues = validate_config({"max_debat_rounds": 2})
        assert len(issues) == 1
        assert "max_debate_rounds" in issues[0].message

    def test_unknown_key_never_raises_even_in_strict_mode(self):
        # Unknown keys are never fatal — see ConfigValidationError's docstring.
        issues = validate_config({"totally_made_up_key": 1}, strict=True)
        assert issues[0].severity == "warning"


@pytest.mark.unit
class TestRangeValidation:
    def test_out_of_range_probability_is_an_error(self):
        issues = validate_config({"trade_filter_threshold": 1.5})
        errors = [i for i in issues if i.severity == "error"]
        assert len(errors) == 1
        assert "trade_filter_threshold" in errors[0].message

    def test_out_of_range_percentage_is_an_error(self):
        issues = validate_config({"max_position_size_pct": 150.0})
        errors = [i for i in issues if i.severity == "error"]
        assert len(errors) == 1

    def test_wrong_type_is_an_error(self):
        issues = validate_config({"max_debate_rounds": "not a number"})
        errors = [i for i in issues if i.severity == "error"]
        assert len(errors) == 1

    def test_debate_context_mode_rejects_unknown_value(self):
        issues = validate_config({"debate_context_mode": "sparse"})
        errors = [i for i in issues if i.severity == "error"]
        assert len(errors) == 1

    def test_in_range_values_produce_no_errors(self):
        issues = validate_config({
            "trade_filter_threshold": 0.5,
            "max_position_size_pct": 25.0,
            "debate_context_mode": "digest",
        })
        assert [i for i in issues if i.severity == "error"] == []


@pytest.mark.unit
class TestStrictMode:
    def test_warn_only_by_default_does_not_raise(self):
        # Should not raise despite the out-of-range value.
        validate_config({"trade_filter_threshold": 1.5})

    def test_strict_true_raises_on_value_error(self):
        with pytest.raises(ConfigValidationError):
            validate_config({"trade_filter_threshold": 1.5}, strict=True)

    def test_strict_config_key_triggers_strict_mode(self):
        with pytest.raises(ConfigValidationError):
            validate_config({"trade_filter_threshold": 1.5, "strict_config": True})

    def test_env_var_triggers_strict_mode(self, monkeypatch):
        monkeypatch.setenv("TRADINGAGENTS_STRICT_CONFIG", "1")
        with pytest.raises(ConfigValidationError):
            validate_config({"trade_filter_threshold": 1.5})

    def test_strict_mode_does_not_raise_on_clean_config(self):
        validate_config(DEFAULT_CONFIG, strict=True)


@pytest.mark.unit
class TestConfigReferenceDoc:
    def test_generates_a_row_per_schema_field(self):
        markdown = generate_config_reference_markdown()
        for name in TradingAgentsConfig.model_fields:
            assert f"`{name}`" in markdown, f"{name} missing from generated docs"

    def test_env_override_column_populated_for_known_env_vars(self):
        markdown = generate_config_reference_markdown()
        assert "`TRADINGAGENTS_LLM_PROVIDER`" in markdown

    def test_committed_doc_matches_generator_output(self):
        """CI staleness gate: docs/CONFIG_REFERENCE.md must match what the
        schema generates right now, or someone edited the schema without
        regenerating (or edited the doc by hand)."""
        from pathlib import Path

        doc_path = Path(__file__).resolve().parent.parent / "docs" / "CONFIG_REFERENCE.md"
        assert doc_path.is_file(), "docs/CONFIG_REFERENCE.md is missing; run generate-docs"
        assert doc_path.read_text(encoding="utf-8") == generate_config_reference_markdown()


@pytest.mark.unit
class TestCLI:
    def test_check_command_exits_zero_on_valid_config(self, capsys):
        from tradingagents.config_schema import main

        rc = main(["check"])
        assert rc == 0
        assert "OK" in capsys.readouterr().out

    def test_generate_docs_check_exits_zero_when_up_to_date(self, capsys):
        from tradingagents.config_schema import main

        rc = main(["generate-docs", "--check"])
        assert rc == 0
        assert "OK" in capsys.readouterr().out


@pytest.mark.unit
class TestTradingAgentsGraphIntegration:
    def _build_graph(self, tmp_path, monkeypatch, config):
        from unittest.mock import MagicMock

        from tradingagents.graph import trading_graph as tg

        monkeypatch.setattr(
            tg, "create_llm_client",
            lambda **kw: MagicMock(get_llm=lambda: MagicMock()),
        )
        monkeypatch.setattr(
            tg.GraphSetup, "setup_graph",
            lambda self, selected_analysts=None, **kw: MagicMock(),
        )
        return tg.TradingAgentsGraph(config=config)

    def test_graph_construction_does_not_raise_on_valid_config(self, tmp_path, monkeypatch):
        cfg = dict(DEFAULT_CONFIG)
        cfg["audit_dir"] = str(tmp_path)
        cfg["audit_full_trace_enabled"] = False
        cfg["checkpoint_enabled"] = False
        self._build_graph(tmp_path, monkeypatch, cfg)  # must not raise

    def test_graph_construction_warns_but_does_not_raise_on_bad_config_by_default(
        self, tmp_path, monkeypatch
    ):
        cfg = dict(DEFAULT_CONFIG)
        cfg["audit_dir"] = str(tmp_path)
        cfg["audit_full_trace_enabled"] = False
        cfg["checkpoint_enabled"] = False
        cfg["trade_filter_threshold"] = 5.0  # out of [0, 1] range
        self._build_graph(tmp_path, monkeypatch, cfg)  # must not raise

    def test_graph_construction_raises_on_bad_config_in_strict_mode(self, tmp_path, monkeypatch):
        cfg = dict(DEFAULT_CONFIG)
        cfg["audit_dir"] = str(tmp_path)
        cfg["audit_full_trace_enabled"] = False
        cfg["checkpoint_enabled"] = False
        cfg["trade_filter_threshold"] = 5.0
        cfg["strict_config"] = True
        with pytest.raises(ConfigValidationError):
            self._build_graph(tmp_path, monkeypatch, cfg)
