from typing import Annotated, Any

from langgraph.graph import MessagesState
from typing_extensions import TypedDict


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    instrument_context: Annotated[str, "Deterministic ticker identity resolved at run start"]
    trade_date: Annotated[str, "What date we are trading at"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    target_profile: Annotated[dict, "Target investor profile, horizon, benchmark, and risk appetite"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    options_report: Annotated[str, "Report from the Options Analyst"]
    esg_report: Annotated[str, "Report from the ESG Analyst"]
    derivatives_report: Annotated[str, "Report from the Derivatives Analyst (options/futures structure, IV, greeks, flow)"]

    # Cross-factor conflict report computed after analysts, before the debate (P0.1)
    conflict_report: Annotated[
        dict[str, Any], "Cross-factor divergence signals/conflicts/notes for downstream agents"
    ]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_constraints: Annotated[
        dict,
        "Risk constraints injected at session start and re-injected at prompt time",
    ]
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    source_objects: Annotated[list, "Structured source objects available to the Portfolio Manager"]
    recommendation_scorecard: Annotated[dict, "Deterministic audit scorecard used for recommendation reconciliation"]
    pre_synthesis_scope_audit: Annotated[dict, "Deterministic ticker/entity scope audit created before final synthesis"]
    raw_tool_outputs: Annotated[list, "Raw tool output source objects captured from graph tool messages"]
    raw_tool_seen_ids: Annotated[list, "Tool call IDs already captured as raw evidence"]
    source_registry: Annotated[dict, "Normalized source registry used for citation validation"]
    claim_graph: Annotated[dict, "Structured claim graph extracted from reports and source objects"]
    skill_registry: Annotated[dict, "Structured skill registry spanning QA, claims, regime, and judge"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
    user_research_report: Annotated[str, "User-uploaded research notes summary, joined across files"]
    tool_errors: Annotated[list, "List of tool error payloads captured during the run"]
    tool_call_count: Annotated[int, "Total number of tool calls made during the run"]
    error_count: Annotated[int, "Total number of tool calls that returned error payloads"]
    data_quality: Annotated[str, "high | medium | low | unknown"]
    structured_valid: Annotated[bool, "Whether the final decision path was fully structured-output valid"]
    research_manager_structured_valid: Annotated[bool, "Whether Research Manager produced structured output successfully"]
    trader_structured_valid: Annotated[bool, "Whether Trader produced structured output successfully"]
    portfolio_manager_structured_valid: Annotated[bool, "Whether Portfolio Manager produced structured output successfully"]
    confidence_score: Annotated[float, "0..1 confidence score based on data quality and agreement"]
    trade_levels: Annotated[object, "Last captured suggest_trade_levels payload (if any)"]
    trade_filter_score: Annotated[float, "0..1 selectivity score for whether to take the trade"]
    trade_filter_pass: Annotated[bool, "Whether the trade_filter_score met the threshold"]
    trade_filter_reasons: Annotated[list, "Human-readable reasons supporting the trade_filter_score"]
    trade_filtered_out: Annotated[bool, "Whether the trade was filtered out (hard filters or score below threshold)"]
    trade_filter_details: Annotated[object, "Full trade filter output including sub-scores and hard reject reasons"]
    market_state: Annotated[dict[str, Any], "Structured latent market state for backtest persistence"]
    structure_analysis: Annotated[dict[str, Any], "Deterministic OHLCV structure analysis for backtest persistence"]
    feature_snapshot: Annotated[dict[str, Any], "Machine-readable historical feature snapshot for offline policy search"]
    structured_strategy: Annotated[dict[str, Any], "Structured strategy for backtest persistence"]

    # Optional current position context for the analyzed ticker
    holdings_info: Annotated[dict[str, float], "Current holdings context: quantity and avg_buy_price"]

    # Backtest-only: rolling-window realized PnL summary from prior strategies
    trading_history_summary: Annotated[
        dict[str, Any], "Rolling-window PnL summary of prior backtest trades"
    ]
    # Backtest-only: orders from the previous strategy that never filled
    prior_pending_orders: Annotated[
        list[dict[str, Any]], "Unfilled orders carried over from the previous strategy"
    ]

    # Trading mode: 'live' for real-time analysis or 'backtest' for historical replay
    trading_mode: Annotated[str, "Trading mode: 'live' or 'backtest'"]

    # Monster Stock / TraderLion framework outputs
    monster_stock_score: Annotated[dict[str, Any], "Serialized MonsterStockScore from the scoring engine"]
    group_sector_report: Annotated[str, "Report from the Group & Sector Leadership Analyst"]
    market_phase_report: Annotated[str, "Report from the Market Phase Analyst"]
    postmortem_report: Annotated[str, "Post-mortem analysis from the Post-Mortem Analyst"]
    postmortem_past_recommendation: Annotated[str, "Past recommendation text for post-mortem input"]
    postmortem_outcome_data: Annotated[str, "Outcome data for post-mortem input"]
