"""Build a Jekyll-friendly index.md for GitHub Pages from docs/ runs.

Each run lives at ``docs/<TICKER>_<DATE>_<MODEL>_<TS>/complete_report.md``.
Jekyll (jekyll-theme-minimal, configured in ``docs/_config.yml``) renders
those markdown files as standalone subpages. This script only writes the
top-level ``docs/index.md`` — a TOC grouped by ticker that links to each
run's ``complete_report.md``.

Run locally:

    python scripts/build_reports_site.py

Idempotent: rewrites ``docs/index.md`` in place, never touches the run
markdown.
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import NamedTuple


REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs"

RUN_DIR_RE = re.compile(
    r"^(?P<ticker>[A-Za-z0-9.\-]+)_(?P<date>\d{8})_(?P<model>.+?)"
    r"(?:_(?P<run_date>\d{8})_(?P<run_time>\d{6}))?$"
)

DISCLAIMER = (
    "> **Disclaimer:** Reports below are generated by an LLM-based research "
    "agent for experimentation. They are **not** financial advice. Treat the "
    "analysis as a synthetic exercise.\n"
)


class Run(NamedTuple):
    ticker: str
    analysis_date: str   # YYYY-MM-DD
    model: str
    run_started: str     # YYYY-MM-DD HH:MM:SS
    folder_name: str     # used in URLs


def parse_run_folder(path: Path) -> Run | None:
    if not path.is_dir():
        return None
    m = RUN_DIR_RE.match(path.name)
    if not m:
        return None
    date = m.group("date")
    analysis_date = f"{date[:4]}-{date[4:6]}-{date[6:8]}"
    rd, rt = m.group("run_date"), m.group("run_time")
    if rd and rt:
        run_started = f"{rd[:4]}-{rd[4:6]}-{rd[6:8]} {rt[:2]}:{rt[2:4]}:{rt[4:6]}"
    else:
        run_started = datetime.fromtimestamp(path.stat().st_mtime).strftime(
            "%Y-%m-%d %H:%M:%S"
        )
    return Run(
        ticker=m.group("ticker").upper(),
        analysis_date=analysis_date,
        model=m.group("model"),
        run_started=run_started,
        folder_name=path.name,
    )


def build_index(runs: list[Run]) -> str:
    by_ticker: dict[str, list[Run]] = defaultdict(list)
    for r in runs:
        by_ticker[r.ticker].append(r)

    lines = [
        "---",
        "layout: default",
        'title: "TradingAgents Reports"',
        "---",
        "",
        "# TradingAgents Reports",
        "",
        f"_{len(runs)} runs across {len(by_ticker)} tickers._",
        "",
        DISCLAIMER,
    ]
    for ticker in sorted(by_ticker):
        ticker_runs = sorted(
            by_ticker[ticker],
            key=lambda r: (r.analysis_date, r.run_started),
            reverse=True,
        )
        lines.append(f"## {ticker}")
        lines.append("")
        for r in ticker_runs:
            link = f"./{r.folder_name}/complete_report.md"
            lines.append(
                f"- [{r.analysis_date}]({link}) "
                f"&middot; `{r.model}` "
                f"<span style=\"opacity:.6\">&middot; {r.run_started}</span>"
            )
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    if not DOCS_DIR.is_dir():
        print(f"docs/ not found at {DOCS_DIR}", file=sys.stderr)
        return 1

    runs: list[Run] = []
    for child in sorted(DOCS_DIR.iterdir()):
        run = parse_run_folder(child)
        if run is None:
            continue
        runs.append(run)

    if not runs:
        print("No run folders found under docs/.", file=sys.stderr)
        return 1

    (DOCS_DIR / "index.md").write_text(build_index(runs), encoding="utf-8")
    print(f"Wrote docs/index.md with {len(runs)} runs across "
          f"{len({r.ticker for r in runs})} tickers")
    return 0


if __name__ == "__main__":
    sys.exit(main())
